{
  "hash": "b1e6fd273dc89fdfbd7a86aa6d09ab0e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"03: Spatio-Temporal Point Patterns Analysis\"\nauthor: \"Chia Ka Ying\"\ndate: \"2026-09-05\"\ndate-modified: \"last-modified\"\nformat: html\nexecute:\n  echo: true\n  eval: true\n  message: false\n  warning: false\n  freeze: true\neditor: visual\n---\n\nSpatio-temporal point patterns capture the interplay between location and timing in real-world occurrences, from environmental disasters to ecological changes. By examining events through both spatial and temporal lenses, we can better understand how localised disturbances form, spread and interact over time. Using various R packages, this assignment explores forest fire occurrences in Kepulauan Bangka Belitung, Indonesia from 1 January 2023 to 31 December 2023 to run a set of spatio-temporal point pattern analyses.\n\nThe research questions for this assignments are as follows:\n\n- Are the locations of forest fire in Kepulauan Bangka Belitung spatial and spatio-temporally independent?\n- If the answer is no, where and when the observed forest fire locations tend to cluster?\n\nThe following data sets will be used:\n- `modis_2023_Indonesia`, a csv file provides locations of forest fire detected from the Moderate Resolution Imaging Spectroradiometer (MODIS) sensor data. The data are downloaded from Fire Information for Resource Management System. The data has forest fires from the whole Indonesia in 2023. For the purpose of this exercise, only forest fires within Kepulauan Bangka Belitung will be used.\n- `Geology Bangka Belitung`, a geological shapefile showing the sub-district boundary of Kepulauan Bangka Belitung. The data set was downloaded from the Indonesia Geospatial portal. I could not locaet the ESRI shapefile mentioned in exercise guide for the sub-district (i.e. kelurahan) boundary of Kepulauan Bangka Belitung. The website has a shapefile for the whole Indonesia and a geological shapefile of the Bangka Belitung Islands Province. I downloaded the geological shapefile as it is the required location for the exercise.\n\n## 1. Importing and Wrangling Geospatial Data Sets\n\nI will first install and load the R packages.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spatstat, sparr, \n               tmap, stpp, tidyverse)\n```\n:::\n\n\n### 1.1 Checking Data Set\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb <- st_read(dsn = \"data/Bangka_Belitung\",\n               layer = \"Geology Bangka Belitung\") %>%\n  st_transform(crs = 32748)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Geology Bangka Belitung' from data source \n  `C:\\kayc134\\ISSS626_kayc\\Hands-on_Ex\\Hands-on_Ex03\\data\\Bangka_Belitung' \n  using driver `ESRI Shapefile'\nSimple feature collection with 33 features and 12 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 104.9592 ymin: -3.961192 xmax: 109.1553 ymax: -1.477503\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n::: callout-note\n## Note\n\nLooking at the details of the shapefile, there are a number of differences with that in the exercise guide:\n\n- Has only 33 features and 12 fields, compared to 297 features and 26 fields.\n- Geometry type is multipolygon instead of polygon.\n- Dimension is XY instead of XYZ\n- Bounding box is \"xmin: 104.9592 ymin: -3.961192 xmax: 109.1553 ymax: -1.477503\" instead of \"xmin: 105.1085 ymin: -3.116593 xmax: 106.8488 ymax: -1.501603\".\n\nAs the exercise uses *st_union* to dissolve the features into a single polygon and drops attribute fields, and the subsequent `kbb_sf` and `kbb_owin` is used as a boundary to show the fire points, I might be able to continue using this geological shapefile. \n\nI will first check the attribute table to check the names of the 12 fields and plot it to see what it looks like with the areas labelled based on the field \"NM_LEMBAR\", which was identified through trial and error.\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(kbb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"SYMBOLS\"    \"NM_LEMBAR\"  \"NO_LEMBAR\"  \"PROJECT\"    \"NAME\"      \n [6] \"FORMATION\"  \"CLASS_LITH\" \"T_CLASS_EN\" \"B_CLASS_EN\" \"DESCRIP1\"  \n[11] \"Shape_Leng\" \"Shape_Area\" \"geometry\"  \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kbb) + tm_polygons(col = \"NM_LEMBAR\")\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n## Note\n\nI managed to find out more about the locations based on a search:\n\nJAMBI:\tJambi province — southern Sumatra mainland\nLAHAT:\tLahat, South Sumatra — mainland\nTULUNG SELAPAN:\tOgan Komering Ilir, South Sumatra — mainland\nPANGKALPINANG:\tCapital city, on Bangka Island\nSUNGAILIAT:\tRegency seat of Bangka Regency, on Bangka Island\nTANJUNG PANDAN:\tRegency seat of Belitung Regency, on Belitung Island\n\nThis means that I am likely to require only PANGKALPINANG and SUNGAILIAT based on the plotted map in the exercise guide, even though TANJUNG PANDAN is the location of Belitung Island. I also note that my plotted map has an additional island on the bottom right, Lepar Island, which is third-largest island in Indonesia's Bangka Belitung province. As it is not categorised separately in `NM_LEMBAR`, I am unable to remove it.\n\nI will plot the fire incidents to confirm the locations to drop.\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf <- read_csv(\"data/modis_2023_Indonesia.csv\") %>%\n  st_as_sf(coords = c(\"longitude\",\"latitude\"), crs = 4326)\n\ntm_shape(kbb %>% filter(NM_LEMBAR %in% c(\"PANGKALPINANG\",\"SUNGAILIAT\"))) +\n  tm_polygons(col = \"NM_LEMBAR\") +\ntm_shape(fire_sf) +\n  tm_dots()\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n### 1.2 Importing Study Area and Converting to owin Object\n\nI will now create the `kbb_sf` shapefile and `kbb_owin` owin object for map plotting. I also included the *st_make_valid* function as there was error with invalid polygon due to duplicated vertex, which could be due to it being a geological layer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_sf <- st_read(dsn = \"data/Bangka_Belitung\",\n               layer = \"Geology Bangka Belitung\") %>%\n  filter(NM_LEMBAR %in% c(\"PANGKALPINANG\", \"SUNGAILIAT\")) %>%\n  st_make_valid() %>%\n  st_union() %>%\n  st_zm(drop = TRUE, what = \"ZM\") %>%\n  st_transform(crs = 32748)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Geology Bangka Belitung' from data source \n  `C:\\kayc134\\ISSS626_kayc\\Hands-on_Ex\\Hands-on_Ex03\\data\\Bangka_Belitung' \n  using driver `ESRI Shapefile'\nSimple feature collection with 33 features and 12 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 104.9592 ymin: -3.961192 xmax: 109.1553 ymax: -1.477503\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nkbb_owin <- as.owin(kbb_sf)\nkbb_owin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwindow: polygonal boundary\nenclosing rectangle: [511926.1, 712204.3] x [9655877, 9834117] units\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(kbb_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"owin\"\n```\n\n\n:::\n:::\n\n\n## 2. Importing and Preparing Forest Fire Data\n\n::: callout-note\n## Note\n\nAs the forest fire data set contains fire incidents for the whole Indonesia in 2023, I will use the *st_filter* function to include only the fire incidents that spatially intersects with `kbb_sf`, which is our required location.\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf <- read_csv(\"data/modis_2023_Indonesia.csv\") %>%\n  st_as_sf(coords = c(\"longitude\",\"latitude\"), crs = 4326) %>%\n  st_transform(crs = 32748) %>%\n  st_filter(kbb_sf)\n```\n:::\n\n\nBecause ppp object only accept numerical or character as mark. The code chunk below is used to convert data type of acq_date to numeric.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf <- fire_sf %>% \n  mutate(DayofYear = yday(acq_date)) %>%\n  mutate(Month_num = month(acq_date)) %>%\n  mutate(Month_fac = month(acq_date, \n                           label = TRUE, \n                           abbr = FALSE))\n```\n:::\n\n\n## 3. Visualising the Fire Points\n\n### 3.1 Overall plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kbb_sf) +\n  tm_polygons() +\ntm_shape(fire_sf) +\n  tm_dots()\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n### 3.2 Visualising geographic distribution of forest fires by month\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kbb_sf)+\n  tm_polygons() +\ntm_shape(fire_sf) +\n  tm_dots(size = 0.1) +\ntm_facets(by=\"Month_fac\", \n            free.coords=FALSE, \n            drop.units = TRUE)\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n## 4. Computing STKDE by Month\n\nMoving beyond static spatial data, a spatio-temporal point process incorporates the element of time, modeling events defined by both their geographic location and moment of occurrence. This approach is important for studying time-sensitive phenomena, including epidemiological outbreaks, species sightings and natural hazards. Given the increasing availability of spatiotemporally tagged data across diverse fields, point pattern analysis has grown significantly in both necessity and capability. Building on recent advancements in R’s spatial ecosystem, this section provides an intuitive, step-by-step application of spatio-temporal analysis. The methods, procedural steps and empirical interpretations are demonstrated using a complete year of forest fire data from Kepulauan Bangka Belitung, Indonesia in 2023.\n\nThrough the analysis, I will answer the following questions:\n\n- Are the locations of forest fire in Kepulauan Bangka Belitung spatial and spatio-temporally independent?\n- If the answer is no, where and when do the observed forest fire locations tend to cluster?\n\n### 4.1 Extracting forest fires by month\n\nI will remove the unwanted fields from `fire_sf` sf data.frame. This is because *.ppp()* only needs the mark and geometry fields from the input sf dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month <- fire_sf %>% \n  select(Month_num)\n```\n:::\n\n\n### 4.2 Creating ppp\n\nI will create a ppp object called `fire_month` from the sf data frame and check whether it is the correct object class.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month_ppp <- as.ppp(fire_month)\nfire_month_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 766 points\nmarks are numeric, of storage type  'double'\nwindow: rectangle = [521564.1, 710514.1] x [9658137, 9828767] units\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(fire_month_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"ppp\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fire_month_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  766 points\nAverage intensity 2.375899e-08 points per square unit\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   8.000   9.000   8.594  10.000  12.000 \n\nWindow: rectangle = [521564.1, 710514.1] x [9658137, 9828767] units\n                    (189000 x 170600 units)\nWindow area = 32240400000 square units\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Note\n\nThe output shows a higher point count of 766, bigger window and window area as compared to the exercise guide. This is likely due to the additional points on Lepar Island.\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nany(duplicated(fire_month_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n### 4.3 Including owin Object\n\nI will now combine the origin_am_ppp and am_owin objects.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month_owin <- fire_month_ppp[kbb_owin]\nsummary(fire_month_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  766 points\nAverage intensity 6.509848e-08 points per square unit\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   8.000   9.000   8.594  10.000  12.000 \n\nWindow: polygonal boundary\n12 separate polygons (no holes)\n            vertices        area relative.area\npolygon 1       1112 11538900000      9.81e-01\npolygon 2          6      766476      6.51e-05\npolygon 3         13     3176410      2.70e-04\npolygon 4          8     1596800      1.36e-04\npolygon 5         11     3660100      3.11e-04\npolygon 6         18     6788640      5.77e-04\npolygon 7          7     1626890      1.38e-04\npolygon 8         89   205704000      1.75e-02\npolygon 9          3      197759      1.68e-05\npolygon 10         4      663918      5.64e-05\npolygon 11        10     2850370      2.42e-04\npolygon 12         6      838021      7.12e-05\nenclosing rectangle: [511926.1, 712204.3] x [9655877, 9834117] units\n                     (200300 x 178200 units)\nWindow area = 11766800000 square units\nFraction of frame area: 0.33\n```\n\n\n:::\n:::\n\n\nAs a good practice, I will use *plot()* to plot ff_owin to examine the correctness of the output object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fire_month_owin)\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n### 4.4 Computing Spatio-Temporal KDE\n\nNext, *spattemp.density()* of sparr package is used to compute the STKDE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_kde <- spattemp.density(fire_month_owin)\nsummary(st_kde)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 15491.17 (spatial)\n  lambda = 0.0301 (temporal)\n\nNo. of observations\n  766 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [511926.1, 712204.3] x [9655877, 9834117]\n\nTemporal bound\n  [1, 12]\n\nEvaluation\n  128 x 128 x 12 trivariate lattice\n  Density range: [5.059389e-27, 7.823236e-10]\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Note\n\nThe output shows a higher point count of 766 instead of 741 and a larger window area compared to the exercise guide. This difference stems from the study area boundary including Lepar Island. Consequently, the expanded geographic boundary includes additional forest fire events.\n\n:::\n\n### 4.5 Plotting the spatio-temporal KDE object\n\nI will use *plot()* of base R to plot the KDE from July to December 2023.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntims <- c(7,8,9,10,11,12)\npar(mfcol=c(2,3))\nfor(i in tims){ \n  plot(st_kde, i, \n       override.par=FALSE, \n       fix.range=TRUE, \n       main=paste(\"KDE at month\",i))\n}\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n## 5. Computing STKDE by Day of Year\n\n### 5.1 Creating ppp object\n\nI will now include a `DayofYear` field in the output ppp object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_yday_ppp <- fire_sf %>% \n  select(DayofYear) %>%\n  as.ppp()\n```\n:::\n\n\n### 5.2 Including owin object\n\nI will be combining the ppp and owin objects.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_yday_owin <- fire_yday_ppp[kbb_owin]\nsummary(fire_yday_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  766 points\nAverage intensity 6.509848e-08 points per square unit\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   10.0   215.0   258.0   246.3   287.8   352.0 \n\nWindow: polygonal boundary\n12 separate polygons (no holes)\n            vertices        area relative.area\npolygon 1       1112 11538900000      9.81e-01\npolygon 2          6      766476      6.51e-05\npolygon 3         13     3176410      2.70e-04\npolygon 4          8     1596800      1.36e-04\npolygon 5         11     3660100      3.11e-04\npolygon 6         18     6788640      5.77e-04\npolygon 7          7     1626890      1.38e-04\npolygon 8         89   205704000      1.75e-02\npolygon 9          3      197759      1.68e-05\npolygon 10         4      663918      5.64e-05\npolygon 11        10     2850370      2.42e-04\npolygon 12         6      838021      7.12e-05\nenclosing rectangle: [511926.1, 712204.3] x [9655877, 9834117] units\n                     (200300 x 178200 units)\nWindow area = 11766800000 square units\nFraction of frame area: 0.33\n```\n\n\n:::\n:::\n\n\n### 5.3 Plotting the spatio-temporal STKDE object\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_yday <- spattemp.density(\n  fire_yday_owin)\nsummary(kde_yday)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 15491.17 (spatial)\n  lambda = 6.3977 (temporal)\n\nNo. of observations\n  766 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [511926.1, 712204.3] x [9655877, 9834117]\n\nTemporal bound\n  [10, 352]\n\nEvaluation\n  128 x 128 x 343 trivariate lattice\n  Density range: [1.584362e-26, 2.59303e-12]\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(kde_yday)\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-6.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-8.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-9.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-10.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-11.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-12.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-13.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-14.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-15.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-16.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-17.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-18.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-19.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-20.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-21.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-22.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-23.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-24.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-25.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-26.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-27.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-28.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-29.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-30.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-31.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-32.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-33.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-34.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-35.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-36.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-37.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-38.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-39.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-40.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-41.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-42.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-43.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-44.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-45.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-46.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-47.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-48.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-49.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-50.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-51.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-52.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-53.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-54.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-55.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-56.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-57.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-58.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-59.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-60.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-61.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-62.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-63.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-64.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-65.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-66.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-67.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-68.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-69.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-70.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-71.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-72.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-73.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-74.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-75.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-76.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-77.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-78.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-79.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-80.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-81.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-82.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-83.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-84.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-85.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-86.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-87.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-88.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-89.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-90.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-91.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-92.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-93.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-94.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-95.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-96.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-97.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-98.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-99.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-100.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-101.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-102.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-103.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-104.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-105.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-106.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-107.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-108.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-109.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-110.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-111.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-112.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-113.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-114.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-115.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-116.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-117.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-118.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-119.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-120.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-121.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-122.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-123.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-124.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-125.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-126.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-127.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-128.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-129.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-130.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-131.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-132.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-133.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-134.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-135.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-136.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-137.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-138.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-139.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-140.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-141.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-142.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-143.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-144.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-145.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-146.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-147.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-148.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-149.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-150.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-151.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-152.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-153.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-154.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-155.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-156.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-157.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-158.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-159.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-160.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-161.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-162.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-163.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-164.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-165.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-166.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-167.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-168.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-169.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-170.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-171.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-172.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-173.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-174.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-175.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-176.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-177.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-178.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-179.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-180.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-181.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-182.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-183.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-184.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-185.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-186.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-187.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-188.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-189.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-190.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-191.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-192.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-193.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-194.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-195.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-196.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-197.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-198.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-199.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-200.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-201.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-202.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-203.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-204.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-205.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-206.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-207.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-208.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-209.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-210.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-211.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-212.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-213.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-214.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-215.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-216.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-217.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-218.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-219.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-220.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-221.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-222.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-223.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-224.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-225.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-226.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-227.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-228.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-229.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-230.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-231.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-232.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-233.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-234.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-235.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-236.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-237.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-238.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-239.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-240.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-241.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-242.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-243.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-244.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-245.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-246.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-247.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-248.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-249.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-250.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-251.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-252.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-253.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-254.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-255.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-256.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-257.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-258.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-259.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-260.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-261.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-262.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-263.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-264.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-265.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-266.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-267.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-268.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-269.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-270.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-271.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-272.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-273.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-274.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-275.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-276.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-277.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-278.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-279.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-280.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-281.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-282.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-283.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-284.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-285.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-286.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-287.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-288.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-289.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-290.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-291.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-292.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-293.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-294.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-295.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-296.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-297.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-298.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-299.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-300.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-301.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-302.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-303.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-304.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-305.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-306.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-307.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-308.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-309.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-310.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-311.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-312.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-313.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-314.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-315.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-316.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-317.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-318.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-319.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-320.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-321.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-322.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-323.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-324.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-325.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-326.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-327.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-328.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-329.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-330.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-331.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-332.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-333.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-334.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-335.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-336.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-337.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-338.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-339.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-340.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-341.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-342.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-23-343.png){width=672}\n:::\n:::\n\n\n## 6. Computing STKDE by Day of Year: Improved Method\n\nThe *BOOT.spattemp()* in sparr package supports bandwidth selection for standalone spatiotemporal density/intensity based on bootstrap estimation of the MISE, providing an isotropic scalar spatial bandwidth and a scalar temporal bandwidth.\n\nI will use *BOOT.spattemp()* to determine both the spatial bandwidth and the scalar temporal bandwidth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nBOOT.spattemp(fire_yday_owin) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInitialising...Done.\nOptimising...\nh = 15491.17 \b; lambda = 16.45391 \nh = 17040.28 \b; lambda = 16.45391 \nh = 15491.17 \b; lambda = 1565.571 \nh = 15878.45 \b; lambda = 791.0123 \nh = 16072.09 \b; lambda = 403.7331 \nh = 16168.91 \b; lambda = 210.0935 \nh = 16217.32 \b; lambda = 113.2737 \nh = 16241.52 \b; lambda = 64.86381 \nh = 16253.62 \b; lambda = 40.65886 \nh = 16259.67 \b; lambda = 28.55638 \nh = 16271.78 \b; lambda = 4.351435 \nh = 16262.7 \b; lambda = 22.50515 \nh = 16268.75 \b; lambda = 10.40267 \nh = 16264.21 \b; lambda = 19.47953 \nh = 16267.24 \b; lambda = 13.42829 \nh = 16264.97 \b; lambda = 17.96672 \nh = 14715.85 \b; lambda = 17.96672 \nh = 13553.64 \b; lambda = 18.72312 \nh = 12779.83 \b; lambda = 17.21031 \nh = 11037.27 \b; lambda = 16.83211 \nh = 9099.737 \b; lambda = 19.10133 \nh = 5904.022 \b; lambda = 20.42503 \nh = 6583.368 \b; lambda = 17.21031 \nh = 3098.233 \b; lambda = 16.45391 \nh = 4645.837 \b; lambda = 19.47953 \nh = 9439.41 \b; lambda = 17.49397 \nh = 6243.695 \b; lambda = 18.81767 \nh = 7042.624 \b; lambda = 18.48675 \nh = 4526.254 \b; lambda = 16.59574 \nh = 7956.366 \b; lambda = 18.47493 \nh = 8415.622 \b; lambda = 19.75136 \nh = 7957.559 \b; lambda = 19.1161 \nh = 8871.301 \b; lambda = 19.10428 \nh = 7499.793 \b; lambda = 18.64113 \nh = 7500.985 \b; lambda = 19.2823 \nh = 7273.295 \b; lambda = 19.68599 \nh = 6815.529 \b; lambda = 19.21102 \nh = 7672.051 \b; lambda = 19.13983 \nh = 7445.553 \b; lambda = 20.18469 \nh = 7418.433 \b; lambda = 20.95647 \nh = 7046.796 \b; lambda = 20.73085 \nh = 7203.11 \b; lambda = 20.33309 \nDone.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         h     lambda \n7445.55291   20.18469 \n```\n\n\n:::\n:::\n\n\n### 6.1 Computing spatio-temporal KDE\n\nI will derive the STKDE  using h and lambda values from previous steps.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_yday <- spattemp.density(fire_yday_owin,\n                             h = 7000,\n                             lambda = 20)\nsummary(kde_yday)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 7000 (spatial)\n  lambda = 20 (temporal)\n\nNo. of observations\n  766 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [511926.1, 712204.3] x [9655877, 9834117]\n\nTemporal bound\n  [10, 352]\n\nEvaluation\n  128 x 128 x 343 trivariate lattice\n  Density range: [1.19522e-21, 2.959259e-12]\n```\n\n\n:::\n:::\n\n\n### 6.2 Plotting the output spatio-temporal KDE\n\nI will use *plot()* of sparr package to plot the output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(kde_yday)\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-6.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-8.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-9.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-10.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-11.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-12.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-13.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-14.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-15.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-16.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-17.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-18.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-19.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-20.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-21.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-22.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-23.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-24.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-25.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-26.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-27.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-28.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-29.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-30.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-31.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-32.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-33.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-34.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-35.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-36.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-37.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-38.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-39.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-40.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-41.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-42.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-43.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-44.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-45.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-46.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-47.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-48.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-49.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-50.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-51.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-52.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-53.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-54.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-55.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-56.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-57.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-58.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-59.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-60.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-61.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-62.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-63.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-64.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-65.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-66.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-67.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-68.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-69.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-70.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-71.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-72.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-73.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-74.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-75.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-76.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-77.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-78.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-79.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-80.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-81.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-82.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-83.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-84.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-85.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-86.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-87.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-88.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-89.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-90.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-91.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-92.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-93.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-94.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-95.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-96.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-97.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-98.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-99.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-100.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-101.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-102.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-103.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-104.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-105.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-106.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-107.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-108.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-109.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-110.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-111.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-112.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-113.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-114.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-115.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-116.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-117.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-118.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-119.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-120.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-121.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-122.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-123.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-124.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-125.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-126.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-127.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-128.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-129.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-130.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-131.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-132.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-133.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-134.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-135.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-136.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-137.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-138.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-139.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-140.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-141.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-142.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-143.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-144.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-145.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-146.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-147.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-148.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-149.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-150.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-151.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-152.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-153.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-154.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-155.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-156.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-157.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-158.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-159.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-160.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-161.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-162.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-163.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-164.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-165.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-166.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-167.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-168.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-169.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-170.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-171.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-172.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-173.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-174.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-175.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-176.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-177.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-178.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-179.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-180.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-181.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-182.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-183.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-184.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-185.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-186.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-187.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-188.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-189.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-190.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-191.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-192.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-193.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-194.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-195.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-196.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-197.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-198.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-199.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-200.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-201.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-202.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-203.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-204.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-205.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-206.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-207.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-208.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-209.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-210.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-211.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-212.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-213.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-214.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-215.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-216.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-217.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-218.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-219.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-220.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-221.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-222.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-223.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-224.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-225.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-226.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-227.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-228.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-229.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-230.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-231.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-232.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-233.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-234.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-235.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-236.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-237.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-238.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-239.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-240.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-241.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-242.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-243.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-244.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-245.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-246.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-247.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-248.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-249.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-250.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-251.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-252.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-253.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-254.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-255.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-256.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-257.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-258.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-259.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-260.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-261.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-262.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-263.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-264.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-265.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-266.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-267.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-268.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-269.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-270.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-271.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-272.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-273.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-274.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-275.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-276.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-277.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-278.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-279.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-280.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-281.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-282.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-283.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-284.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-285.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-286.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-287.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-288.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-289.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-290.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-291.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-292.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-293.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-294.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-295.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-296.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-297.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-298.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-299.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-300.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-301.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-302.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-303.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-304.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-305.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-306.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-307.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-308.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-309.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-310.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-311.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-312.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-313.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-314.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-315.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-316.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-317.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-318.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-319.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-320.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-321.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-322.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-323.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-324.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-325.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-326.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-327.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-328.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-329.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-330.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-331.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-332.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-333.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-334.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-335.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-336.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-337.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-338.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-339.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-340.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-341.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-342.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-26-343.png){width=672}\n:::\n:::\n\n\n## 7. Spatio-Temporal Point Patterns Analysis: stpp methods\n\nIn this section, I will use functions from the stpp package to perform spatio-temporal point patterns analysis.\n\n### 7.1 Preparing spatio-temporal point process object of stpp\n\nStep 1: Extracting forest fire coordinates from the fire point events\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords <- st_coordinates(fire_sf)\n```\n:::\n\n\nStep 2: Creating a data frame by combining the x- and y-coordinates and temporal event. Note that the temporal event must be in integer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_df <- data.frame(\n  x = coords[, 1],  \n  y = coords[, 2],\n  t = fire_sf$`DayofYear`)\n```\n:::\n\n\nStep 3: Creating stpp spatio-temporal object\n\n*as.3dpoint()* of stpp package is used to create stpp spatio-temporal object class. I will also confirm the object class and plot it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_stpp <- as.3dpoints(fire_df)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(fire_stpp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"stpp\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fire_stpp)\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex03_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n### 7.2 Computing spatio-temporal k-function\n\n*STIKhat()* of stpp package is used to compute space-time inhomogeneous K-function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_stik <- STIKhat(fire_stpp)\n```\n:::\n\n\n*plotK()* is used to visualise the output space-time inhomogeneous K-function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotK(kbb_stik)\n```\n:::\n\n\n### 7.3 Interpreting the Plot\n\nIf the contours show high values for small values of uu and vv, it suggests clustering at short spatial and temporal distances, meaning events occur close to each other in both space and time.\n\nIf the contours are flat or show low values, it indicates a more random distribution or a lack of significant clustering at those distances.\n\nThe spatial and temporal extent of clustering can be understood by observing how rapidly the contours increase or decrease as we move along the axes. \n\n::: callout-note\n## Note\n\nIn interpreting the plot, I will first break down each part of the graph:\n\n- X-axis (u): Spatial distance (in spatial units, e.g., meters).\n- Y-axis (v): Temporal distance (in time units, e.g., days).\n- Contour Lines: The estimated value of the space-time K-function \\hat{K}_{ST}(u, v). Higher values indicate a greater expected number of neighboring events occurring within spatial distance u and temporal distance v.\n\nFor small spatial and temporal intervals (u < 10,000 meters and v < 20 days), the contour values remain near zero, indicated by the absence of lines. The lack of high values at these small scales indicates an absence of strong localised space-time clustering at short distances and time frames. Instead, contour values increase progressively toward the upper-right quadrant, reaching values exceeding 3.5e12 at larger spatial distances (u > 30,000) and extended time  (v > 60). This steady gradient demonstrates that event interaction is driven by patterns, such as seasonal weather conditions, rather than localised outbreaks. This is aligned with personal experiences, where haze conditions in Singapore due to regional forest fires tend to happen at certain times of the year.\n\n:::\n\n## 8. References\n\nKam, T. S. Spatio-Temporal Point Patterns Analysis. R for Geospatial Data Science and Analytics. https://r4gdsa.netlify.app/chap06\n\nPeter Hall (1990) “Using the Bootstrap to Estimate Mean Squared Error and Select Smoothing Parameter in Nonparametric Problems”, JOURNAL OF MULTIVARIATE ANALYSIS, Vol. 32, pp. 177-203.",
    "supporting": [
      "Hands-On_Ex03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}