project:
  type: website

website:
  title: "Kay's GeoHub"
  favicon: "images/favicon.png"
  navbar:
    left:
      - text: "Hands-On Exercise"
        menu:
        - text: "01a: Geospatial Data Science with R"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-On_Ex01a.html"
        - text: "01b: Thematic Mapping and GeoVisualisation with R"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-On_Ex01b.html"
        - text: "02a: First Order Spatial Points Analysis Methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-On_Ex02a.html"
        - text: "02b: Second Order Spatial Points Analysis Methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-On_Ex02b.html"
        - text: "03: Spatio-Temporal Point Patterns Analysis"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-On_Ex03.html"
        - text: "Hands-On Exercise 04"
        - text: "Hands-On Exercise 05"
        - text: "Hands-On Exercise 06"
        - text: "Hands-On Exercise 07"
        - text: "Hands-On Exercise 08"
        - text: "Hands-On Exercise 09"
        - text: "Hands-On Exercise 10"
      - text: "In-Class Exercise"
        menu:
        - text: "In-Class Exercise 01"
        - text: "In-Class Exercise 02"
        - text: "In-Class Exercise 03"
        - text: "In-Class Exercise 04"
        - text: "In-Class Exercise 05"
        - text: "In-Class Exercise 06"
        - text: "In-Class Exercise 07"
        - text: "In-Class Exercise 08"
        - text: "In-Class Exercise 09"
        - text: "In-Class Exercise 10"
      - text: "Take-Home Exercise"
        menu:
        - text: "Take-Home Exercise 01"
        - text: "Take-Home Exercise 02"
        - text: "Take-Home Exercise 03"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true

execute: 
  echo: true
  warning: false
  message: false
  freeze: auto

editor: visual

