project:
  type: website

website:
  title: "Kay's GeoHub"
  favicon: "images/favicon.png"
  navbar:
    left:
      - text: "Hands-On Exercise"
        menu:
        - text: "01a: Geospatial Data Science with R"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-On_Ex01a.html"
        - text: "01b: Thematic Mapping and GeoVisualisation with R"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-On_Ex01b.html"
        - text: "02a: First Order Spatial Points Analysis Methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-On_Ex02a.html"
        - text: "02b: Second Order Spatial Points Analysis Methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-On_Ex02b.html"
        - text: "03: Spatio-Temporal Point Patterns Analysis"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-On_Ex03.html"
        - text: "04a: Network Constrained Spatial Point Patterns Analysis"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-On_Ex04a.html"
        - text: "04b: Spatial Weights and Applications"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-On_Ex04b.html"
        - text: "05a: Global Measures of Spatial Autocorrelation"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-On_Ex05a.html"
        - text: "05b: Local Measures of Spatial Autocorrelation"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-On_Ex05b.html"
        - text: "Hands-On Exercise 06"
        - text: "Hands-On Exercise 07"
        - text: "Hands-On Exercise 08"
        - text: "Hands-On Exercise 09"
        - text: "Hands-On Exercise 10"
      - text: "In-Class Exercise"
        menu:
        - text: "04: Geographically Weighted Summary Statistics"
          href: "In-Class_Ex/In-Class_Ex04/In-Class_Ex04.html"
        - text: "05: Global and Local Spatial Analysis"
          href: "In-Class_Ex/In-Class_Ex05/In-Class_Ex05.html"
      - text: "Take-Home Exercise"
        menu:
        - text: "Study on Road Accidents in Bangkok Greater Metropolitan Area"
          href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true

execute: 
  echo: true
  warning: false
  message: false
  freeze: auto

editor: visual

