{
  "hash": "5f9e66e4216f75f661f6552d68d0fd65",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"05a: Global Measures of Spatial Autocorrelation\"\nauthor: \"Chia Ka Ying\"\ndate: \"2026-09-19\"\ndate-modified: \"last-modified\"\nformat: html\nexecute:\n  echo: true\n  eval: true\n  message: false\n  warning: false\n  freeze: true\neditor: visual\n---\n\nThis exercise will be computing Global Measures of Spatial Autocorrelation (GMSA) by using **spdep** package. By the end to this hands-on exercise, you will be able to:\n\n- import geospatial data using appropriate function(s) of **sf** package,\n\n- import csv file using appropriate function of **readr** package,\n\n- perform relational join using appropriate join function of **dplyr** package,\n\n- compute Global Spatial Autocorrelation (GSA) statistics by using appropriate functions of **spdep** package,\n\n  - plot Moran scatterplot,\n\n  - compute and plot spatial correlogram using appropriate function of **spdep** package.\n\n- provide statistically correct interpretation of GSA statistics.\n\n## 1. Getting Started\n\nIn spatial policy, one of the main development objective of the local government and planners is to ensure equal distribution of development in the province. In this case study, we are interested to examine the spatial pattern of a selected development indicator (i.e., GDP per capita) of Hunan Provice, People Republic of China, and to do the following:\n\n- To apply appropriate spatial statistical methods to discover if development are evenly distributed geographically.\n- If not, to find out whether there is sign of spatial clustering.\n- And if yes, to find out where are these clusters.\n\nThe following data sets will be used:\n\nHunan county boundary layer. This is a geospatial data set in ESRI shapefile format. Hunan_2012.csv: This csv file contains selected Hunan’s local development indicators in 2012.\n\nI will now import the required packages to perform the study.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spdep, tmap, tidyverse)\n```\n:::\n\n\n## 2. Preparaing the Data\n\n### 2.1 Importing the Data\n\nI will now import `hunan` and `hunan2012`, which are a shapefile and csv respectively.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(dsn = \"data/geospatial\", \n                 layer = \"Hunan\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Hunan' from data source \n  `C:\\kayc134\\ISSS626_kayc\\Hands-on_Ex\\Hands-on_Ex05\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 88 features and 7 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan2012 <- read_csv(\"data/aspatial/Hunan_2012.csv\")\n```\n:::\n\n\n### 2.2 Performing Relational Join\n\nI will update the attribute table of the `hunan` SpatialPolygonsDataFrame with the attribute fields of `hunan2012` dataframe using *left_join()*. Prior to doing so, I will do a check of the column names and index for reference in the argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(Index = 1:ncol(left_join(hunan, hunan2012)), \n           Name = names(left_join(hunan, hunan2012)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Index        Name\n1      1      NAME_2\n2      2        ID_3\n3      3      NAME_3\n4      4   ENGTYPE_3\n5      5  Shape_Leng\n6      6  Shape_Area\n7      7      County\n8      8        City\n9      9    avg_wage\n10    10    deposite\n11    11         FAI\n12    12     Gov_Rev\n13    13     Gov_Exp\n14    14         GDP\n15    15       GDPPC\n16    16         GIO\n17    17        Loan\n18    18       NIPCR\n19    19         Bed\n20    20         Emp\n21    21        EmpR\n22    22       EmpRT\n23    23     Pri_Stu\n24    24     Sec_Stu\n25    25   Household\n26    26 Household_R\n27    27        NOIP\n28    28       Pop_R\n29    29        RSCG\n30    30       Pop_T\n31    31        Agri\n32    32     Service\n33    33    Disp_Inc\n34    34        RORP\n35    35      ROREmp\n36    36    geometry\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- left_join(hunan, hunan2012) %>%\n  select(1:4, 7, 15)\n```\n:::\n\n\n### 2.3 Visualising Regional Development Indicator\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequal <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"equal\",\n                n = 5,\n                values = \"brewer.blues\")) +\n  tm_borders(fiil_alpha = 0.5) + \n  tm_layout(legend.position = c(\"left\", \"bottom\"), \n            main.title = \"Equal interval classification\")\n\nquantile <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\",\n                n = 5)) +\n  tm_borders(fiil_alpha = 0.5) + \n  tm_layout(legend.position = c(\"left\", \"bottom\"), \n            main.title = \"Quantile classification\")\n\ntmap_arrange(equal, \n             quantile, \n             asp=1, \n             ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex05a_files/figure-html/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n\n## 3. Global Measures of Spatial Autocorrelation\n\nIn this section, I will compute global spatial autocorrelation statistics and perform spatial complete randomness test for global spatial autocorrelation.\n\n### 3.1 Computing Contiguity Spatial Weights\n\nTo compute global spatial autocorrelation statistics, a spatial weights matrix must first be constructed to define the spatial relationships and neighbourhood structure among the geographical units (i.e., counties) in the study area.\n\nI will use the *poly2nb()* function from the spdep package to compute a contiguity-based neighbour list using shared boundary criteria. By default, the queen argument is set to TRUE, which includes all contiguous boundaries—both shared edges and single shared vertices to identify first-order spatial neighbours.\n\n::: callout-note\n## Note\n\nPlease note that 3.1 and 3.2 were also performed in Hands-On Exercise 4b if you wish to refer to how it is used Spatial Weights and Application.\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- poly2nb(hunan, \n                queen=TRUE)\nsummary(wm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n:::\n\nThe summary report shows that there are 88 area units in Hunan. The most connected area unit has 11 neighbours. There are two area units with only one neighbour.\n\n## 3.2 Row-standardised weights matrix\n\nNext, I will assign weights to each neighboring polygon. In our case, each neighboring polygon will be assigned equal weight using style=“W”. This is accomplished by assigning the fraction 1/(#ofneighbors) to each neighboring county then summing the weighted income values. While this is the most intuitive way to summarise the neighbors’ values, the drawback is that polygons along the edges of the study area will base their lagged values on fewer polygons thus potentially over- or under-estimating the true nature of the spatial autocorrelation in the data. For this example, we will stick with the style=“W” option for simplicity’s sake but note that other more robust options are available, notably style=“B”.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_q <- nb2listw(wm_q, \n                   style=\"W\", \n                   zero.policy = TRUE)\nrswm_q\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \n\nWeights style: W \nWeights constants summary:\n   n   nn S0       S1       S2\nW 88 7744 88 37.86334 365.9147\n```\n\n\n:::\n:::\n\n\n## 4. Global Measures of Spatial Autocorrelation: Moran’s I\n\n### 4.1 Maron’s I test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoran.test(hunan$GDPPC, \n           listw=rswm_q, \n           zero.policy = TRUE, \n           na.action=na.omit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  hunan$GDPPC  \nweights: rswm_q    \n\nMoran I statistic standard deviate = 4.7351, p-value = 1.095e-06\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.300749970      -0.011494253       0.004348351 \n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Note\n\nWith a p-value of < 0.01, we can reject the null hypothesis of spatial randomness. The Moran I statistic value of 0.30075 is positive, and greater than the expected value of -0.0115 under spatial randomness, showing a statistically significant positive spatial correlation. \n\n:::\n\n### 4.2 Computing Monte Carlo Moran’s I\n\nI will now use *moran.mc()* to perform permutation test, using a total of 1,000 simulations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm= moran.mc(hunan$GDPPC, \n                listw=rswm_q, \n                nsim=999, \n                zero.policy = TRUE, \n                na.action=na.omit)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.30075, observed rank = 1000, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Note\n\nThe results are similar even with 1,000 simulations, where the statistic is also 0.30075.\n\n:::\n\n### 4.3 Visualising Monte Carlo Moran’s I\n\nI will now examine the simulated Moran’s I test statistics in greater detail. This can be achieved by plotting the distribution of the statistical values as a histogram by using the code chunk below using *hist()* and *abline()*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.01504572\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.004371574\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-0.18339 -0.06168 -0.02125 -0.01505  0.02611  0.27593 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(bperm$res, \n     freq=TRUE, \n     breaks=20, \n     xlab=\"Simulated Moran's I\")\nabline(v=0, \n       col=\"red\") \n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex05a_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n## 5. Global Measures of Spatial Autocorrelation: Geary’s C\n\n### 5.1 Geary’s C Test\n\nI will perform Geary’s C test for spatial autocorrelation by using *geary.test()* of spdep.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeary.test(hunan$GDPPC, listw=rswm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  hunan$GDPPC \nweights: rswm_q   \n\nGeary C statistic standard deviate = 3.6108, p-value = 0.0001526\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n        0.6907223         1.0000000         0.0073364 \n```\n\n\n:::\n:::\n\n\n### 5.2 Computing Monte Carlo Geary’s C\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm=geary.mc(hunan$GDPPC, \n               listw=rswm_q, \n               nsim=999)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.69072, observed rank = 1, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n### 5.3 Visualising the Monte Carlo Geary’s C\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.004402\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.007436493\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.7142  0.9502  1.0052  1.0044  1.0595  1.2722 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(bperm$res, freq=TRUE, breaks=20, xlab=\"Simulated Geary c\")\nabline(v=1, col=\"red\") \n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex05a_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n## 6. Spatial Correlogram\n\nSpatial correlograms are great to examine patterns of spatial autocorrelation in data or model residuals. They show how correlated are pairs of spatial observations when you increase the distance (lag) between them, by plotting some index of autocorrelation (Moran’s I or Geary’s c) against distance. Although correlograms are not as fundamental as variograms (a keystone concept of geostatistics), they are very useful as an exploratory and descriptive tool. For this purpose they actually provide richer information than variograms.\n\n### 6.1 Compute Moran’s I correlogram\n\nI will be computing a 6-lag spatial correlogram of GDPPC, using the global spatial autocorrelation in Moran's I.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMI_corr <- sp.correlogram(wm_q, \n                          hunan$GDPPC, \n                          order=6, \n                          method=\"I\", \n                          style=\"W\")\nplot(MI_corr)\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex05a_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nPlotting the output might not allow us to provide complete interpretation. This is because not all autocorrelation values are statistically significant. Hence, it is important for us to examine the full analysis report by printing out the analysis results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(MI_corr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial correlogram for hunan$GDPPC \nmethod: Moran's I\n         estimate expectation   variance standard deviate Pr(I) two sided    \n1 (88)  0.3007500  -0.0114943  0.0043484           4.7351       2.189e-06 ***\n2 (88)  0.2060084  -0.0114943  0.0020962           4.7505       2.029e-06 ***\n3 (88)  0.0668273  -0.0114943  0.0014602           2.0496        0.040400 *  \n4 (88)  0.0299470  -0.0114943  0.0011717           1.2107        0.226015    \n5 (88) -0.1530471  -0.0114943  0.0012440          -4.0134       5.984e-05 ***\n6 (88) -0.1187070  -0.0114943  0.0016791          -2.6164        0.008886 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n### 6.2 Compute Geary’s C correlogram and plot\n\nI will now be using *sp.correlogram()* of spdep package to compute a 6-lag spatial correlogram of GDPPC, using the global spatial autocorrelation in Geary’s C. I will also print the analysis report.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGC_corr <- sp.correlogram(wm_q, \n                          hunan$GDPPC, \n                          order=6, \n                          method=\"C\", \n                          style=\"W\")\nplot(GC_corr)\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex05a_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(GC_corr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial correlogram for hunan$GDPPC \nmethod: Geary's C\n        estimate expectation  variance standard deviate Pr(I) two sided    \n1 (88) 0.6907223   1.0000000 0.0073364          -3.6108       0.0003052 ***\n2 (88) 0.7630197   1.0000000 0.0049126          -3.3811       0.0007220 ***\n3 (88) 0.9397299   1.0000000 0.0049005          -0.8610       0.3892612    \n4 (88) 1.0098462   1.0000000 0.0039631           0.1564       0.8757128    \n5 (88) 1.2008204   1.0000000 0.0035568           3.3673       0.0007592 ***\n6 (88) 1.0773386   1.0000000 0.0058042           1.0151       0.3100407    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n",
    "supporting": [
      "Hands-On_Ex05a_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}