<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Chia Ka Ying">
<meta name="dcterms.date" content="2026-09-12">

<title>01: Study on Road Accidents in Bangkok Greater Metropolitan Area – Kay’s GeoHub</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-bcaea1afbde5c3fcfe46a7eae4a52071.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Kay’s GeoHub</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-On Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-On_Ex01a.html">
 <span class="dropdown-text">01a: Geospatial Data Science with R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-On_Ex01b.html">
 <span class="dropdown-text">01b: Thematic Mapping and GeoVisualisation with R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-On_Ex02a.html">
 <span class="dropdown-text">02a: First Order Spatial Points Analysis Methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-On_Ex02b.html">
 <span class="dropdown-text">02b: Second Order Spatial Points Analysis Methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-On_Ex03.html">
 <span class="dropdown-text">03: Spatio-Temporal Point Patterns Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-On_Ex04a.html">
 <span class="dropdown-text">04a: Network Constrained Spatial Point Patterns Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-On_Ex04b.html">
 <span class="dropdown-text">04b: Spatial Weights and Applications</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-On_Ex05a.html">
 <span class="dropdown-text">05a: Global Measures of Spatial Autocorrelation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-On_Ex05b.html">
 <span class="dropdown-text">05b: Local Measures of Spatial Autocorrelation</span></a>
  </li>  
        <li class="dropdown-header">Hands-On Exercise 06</li>
        <li class="dropdown-header">Hands-On Exercise 07</li>
        <li class="dropdown-header">Hands-On Exercise 08</li>
        <li class="dropdown-header">Hands-On Exercise 09</li>
        <li class="dropdown-header">Hands-On Exercise 10</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-Class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-Class_Ex/In-Class_Ex04/In-Class_Ex04.html">
 <span class="dropdown-text">04: Geographically Weighted Summary Statistics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-Class_Ex/In-Class_Ex05/In-Class_Ex05.html">
 <span class="dropdown-text">05: Global and Local Spatial Analysis</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-Home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html">
 <span class="dropdown-text">Study on Road Accidents in Bangkok Greater Metropolitan Area</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-and-study-context" id="toc-introduction-and-study-context" class="nav-link active" data-scroll-target="#introduction-and-study-context">1. Introduction and Study Context</a></li>
  <li><a href="#research-questions-and-objectives" id="toc-research-questions-and-objectives" class="nav-link" data-scroll-target="#research-questions-and-objectives">2. Research Questions and Objectives</a></li>
  <li><a href="#data-and-scope-of-study" id="toc-data-and-scope-of-study" class="nav-link" data-scroll-target="#data-and-scope-of-study">3. Data and Scope of Study</a></li>
  <li><a href="#data-sets" id="toc-data-sets" class="nav-link" data-scroll-target="#data-sets">3.1 Data Sets</a></li>
  <li><a href="#point-event-definition" id="toc-point-event-definition" class="nav-link" data-scroll-target="#point-event-definition">3.2 Point Event Definition</a></li>
  <li><a href="#data-quality-handling-applied-to-point-events" id="toc-data-quality-handling-applied-to-point-events" class="nav-link" data-scroll-target="#data-quality-handling-applied-to-point-events">3.3 Data-Quality Handling Applied to Point Events:</a></li>
  <li><a href="#spatial-study-window" id="toc-spatial-study-window" class="nav-link" data-scroll-target="#spatial-study-window">3.4 Spatial Study Window</a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">4. Data Preparation</a>
  <ul class="collapse">
  <li><a href="#geographical-boundary-of-bmr" id="toc-geographical-boundary-of-bmr" class="nav-link" data-scroll-target="#geographical-boundary-of-bmr">4.1 Geographical Boundary of BMR</a></li>
  <li><a href="#road-networks-in-bmr" id="toc-road-networks-in-bmr" class="nav-link" data-scroll-target="#road-networks-in-bmr">4.2 Road Networks in BMR</a></li>
  <li><a href="#traffic-accidents-in-bmr" id="toc-traffic-accidents-in-bmr" class="nav-link" data-scroll-target="#traffic-accidents-in-bmr">4.3 2022 Traffic Accidents in BMR</a></li>
  <li><a href="#conversion-to-owin-and-ppp" id="toc-conversion-to-owin-and-ppp" class="nav-link" data-scroll-target="#conversion-to-owin-and-ppp">4.4 Conversion to owin and ppp</a></li>
  </ul></li>
  <li><a href="#first-order-sppa" id="toc-first-order-sppa" class="nav-link" data-scroll-target="#first-order-sppa">5. First-Order SPPA</a>
  <ul class="collapse">
  <li><a href="#quadrat-analysis" id="toc-quadrat-analysis" class="nav-link" data-scroll-target="#quadrat-analysis">5.1 Quadrat Analysis</a></li>
  <li><a href="#network-kernel-density-estimate-nkde" id="toc-network-kernel-density-estimate-nkde" class="nav-link" data-scroll-target="#network-kernel-density-estimate-nkde">5.2 Network Kernel Density Estimate (NKDE)</a></li>
  </ul></li>
  <li><a href="#second-order-sppa" id="toc-second-order-sppa" class="nav-link" data-scroll-target="#second-order-sppa">6. Second-Order SPPA</a>
  <ul class="collapse">
  <li><a href="#network-k-function-analysis" id="toc-network-k-function-analysis" class="nav-link" data-scroll-target="#network-k-function-analysis">6.1 Network K-Function Analysis</a></li>
  <li><a href="#network-g-function" id="toc-network-g-function" class="nav-link" data-scroll-target="#network-g-function">6.2 Network G-Function</a></li>
  </ul></li>
  <li><a href="#value-added-analysis" id="toc-value-added-analysis" class="nav-link" data-scroll-target="#value-added-analysis">7. Value-Added Analysis</a>
  <ul class="collapse">
  <li><a href="#local-morans-i" id="toc-local-morans-i" class="nav-link" data-scroll-target="#local-morans-i">7.1 Local Moran’s I</a></li>
  <li><a href="#network-cross-kg-function-fatal-vs-non-fatal-accidents" id="toc-network-cross-kg-function-fatal-vs-non-fatal-accidents" class="nav-link" data-scroll-target="#network-cross-kg-function-fatal-vs-non-fatal-accidents">7.2 Network Cross-K/G Function: Fatal vs Non-Fatal Accidents</a></li>
  </ul></li>
  <li><a href="#public-safety-planning-and-management-implications" id="toc-public-safety-planning-and-management-implications" class="nav-link" data-scroll-target="#public-safety-planning-and-management-implications">8. Public-Safety Planning and Management Implications</a>
  <ul class="collapse">
  <li><a href="#summary-of-analysis" id="toc-summary-of-analysis" class="nav-link" data-scroll-target="#summary-of-analysis">8.1 Summary of Analysis</a></li>
  <li><a href="#reccommendations" id="toc-reccommendations" class="nav-link" data-scroll-target="#reccommendations">8.2 Reccommendations</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">01: Study on Road Accidents in Bangkok Greater Metropolitan Area</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Chia Ka Ying </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 12, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">September 27, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="introduction-and-study-context" class="level2">
<h2 class="anchored" data-anchor-id="introduction-and-study-context">1. Introduction and Study Context</h2>
<p>Road traffic accidents are among the most persistent and spatially patterned public-safety problems facing rapidly urbanising and urbanised regions. Unlike many other point-based public-safety events, traffic accidents are constrained to occur on the road network rather than freely across the two-dimensional landscape . This structural feature of the data has direct consequences for which analytical methods are valid.</p>
<p>This report investigates the spatial distribution of road traffic accidents recorded in <strong>2022</strong> across the <strong>Bangkok Metropolitan Region (BMR)</strong>, comprising Bangkok, Nonthaburi, Nakhon Pathom, Pathum Thani, Samut Prakan and Samut Sakhon. First-order and second-order spatial point pattern analysis (SPPA), with a network-constrained treatment justified by the road-bound nature of the event will be used.</p>
<p>Please refer to the <a href="https://kay-geohub.vercel.app/Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01_ExSum.html#/title-slide">Executive Summary</a> for the key analysis and recommendations.</p>
</section>
<section id="research-questions-and-objectives" class="level2">
<h2 class="anchored" data-anchor-id="research-questions-and-objectives">2. Research Questions and Objectives</h2>
<p><strong>Primary research questions:</strong></p>
<ol type="a">
<li><p>Do road traffic accidents in the BMR occur with uniform intensity across space, or are they concentrated in identifiable areas (first-order property)?</p></li>
<li><p>Do accidents exhibit evidence of spatial interaction, i.e., clustering, inhibition or approximate randomness, relative to an appropriate network-constrained null model (second-order property)?</p></li>
</ol>
<p><strong>Objectives:</strong></p>
<ol type="a">
<li>Prepare and integrate real-world geospatial data for point-pattern analysis.</li>
<li>Investigate first-order properties of the traffic accident point pattern across space, using both planar (quadrat analysis) and network-constrained (Network Kernel Density Estimation) methods.</li>
<li>Investigate second-order properties of the accident point pattern using network-constrained methods (network K- and G-functions), reflecting the road-bound nature of the event process established in Section 1.</li>
<li>Critically evaluate the assumptions, methodological choices and limitations of the methods used.</li>
<li>Communicate findings through appropriate geovisualisation.</li>
<li>Translate findings into public-safety planning implications.</li>
</ol>
</section>
<section id="data-and-scope-of-study" class="level2">
<h2 class="anchored" data-anchor-id="data-and-scope-of-study">3. Data and Scope of Study</h2>
</section>
<section id="data-sets" class="level2">
<h2 class="anchored" data-anchor-id="data-sets">3.1 Data Sets</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>#</th>
<th>Dataset</th>
<th>Geometry</th>
<th>Role</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>geoBoundaries-THA-ADM1-all.shp</code></td>
<td>Multi-polygon</td>
<td>Define the BMR study region (six provinces)</td>
<td><a href="https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/THA/ADM1/geoBoundaries-THA-ADM1-all.zip">Thailand ADM1 Geoboundaries</a></td>
</tr>
<tr class="even">
<td>2</td>
<td><code>thai_road_accident_2019_2022.csv</code></td>
<td>Point (event)</td>
<td>Provides 2022 traffic accidents</td>
<td><a href="https://www.kaggle.com/datasets/thaweewatboy/thailand-road-accident-2019-2022">Thailand Road Accident 2019 to 2022</a></td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>gis_osm_roads_free_1.shp</code></td>
<td>Line</td>
<td>Provides road networks (main roads)</td>
<td><a href="https://download.geofabrik.de/asia/thailand.html">OpenStreetMap for Thailand</a></td>
</tr>
</tbody>
</table>
</section>
<section id="point-event-definition" class="level2">
<h2 class="anchored" data-anchor-id="point-event-definition">3.2 Point Event Definition</h2>
<p>A point event in this study is a single recorded road traffic accident occurring in 2022 within the BMR, represented by its reported latitude/longitude. The source data records one row per accident and includes information on the type of vehicle, accident details and casualties.</p>
</section>
<section id="data-quality-handling-applied-to-point-events" class="level2">
<h2 class="anchored" data-anchor-id="data-quality-handling-applied-to-point-events">3.3 Data-Quality Handling Applied to Point Events:</h2>
<p>To prepare the data sets for analysis, the following data-quality handling was applied for the traffic accident point event data set <code>thai_road_accident_2019_2022.csv</code>:</p>
<ol type="a">
<li><p><strong>Filtering out point events within boundary and temporal points in 2022:</strong> (see section 4.3.2) Based on the province names under <code>province_en</code> and <code>incident_datetime</code>, observations outside the study area and temporal period are filtered out.</p></li>
<li><p><strong>Missing values:</strong> (see section 4.3.4) There are 189 records that are missing latitude and longitude data in the data set, which were filtered out.</p></li>
<li><p><strong>Erroneous values:</strong> (see section 4.3.4) Under the field <code>number_of_vehicles_involved</code>, there were five records indicating zero vehicles were involved in the traffic accident. The details were explored and these appeared to be data entry errors as the accident descriptions mentioned collisions. These five records were treated as data entry errors but retained, considering there woould not be any analysis involving number of vehicles.</p></li>
<li><p><strong>Duplicate observations:</strong> (see section 4.3.4) Using the values in <code>acc_code</code> which provided a unique ID for each traffic accident, the <em>distinct()</em> function was used to check and remove any duplicate event point. There was no duplicate event point identified.</p></li>
<li><p><strong>Invalid coordinates or geometries:</strong> (see section 4.4) Four event points that were misaligned or located outside the study area were dropped by subsetting the ppp point object against the owin object.</p></li>
<li><p><strong>Overlapping observations:</strong> (see section 4.4) Even after removing duplicate observations, there might be point events of different traffic accidents that overlap. Using <em>rjitter()</em>, any identified overlapping point events would be moved by one meter.</p></li>
</ol>
</section>
<section id="spatial-study-window" class="level2">
<h2 class="anchored" data-anchor-id="spatial-study-window">3.4 Spatial Study Window</h2>
<p>The spatial study window was made up of six BMR provinces (Bangkok, Nonthaburi, Nakhon Pathom, Pathum Thani, Samut Prakan, Samut Sakhon), dissolved into a single polygon. This boundary was used as the owin for planar spatstat analysis and the clipping extent for the road network and traffic accident point events.</p>
</section>
<section id="data-preparation" class="level2">
<h2 class="anchored" data-anchor-id="data-preparation">4. Data Preparation</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, terra, spatstat, spNetwork, tmap, tidyverse, dplyr, units, lubridate)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="geographical-boundary-of-bmr" class="level3">
<h3 class="anchored" data-anchor-id="geographical-boundary-of-bmr">4.1 Geographical Boundary of BMR</h3>
<section id="importing-geographical-boundary-data" class="level4">
<h4 class="anchored" data-anchor-id="importing-geographical-boundary-data">4.1.1 Importing geographical boundary data</h4>
<p>Prior to preparing the geospatial analytical workspace, it is important to check the details of the dataset. This would aid in the extraction of the provinces in BMR into a shapefile <code>bmr</code>.</p>
<p><em>st_transform(crs = 32647)</em> reprojects the data into WGS 84 / UTM Zone 47N (Klokan Technologies GmbH, n.d.).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>adm1 <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/geospatial/geoBoundaries-THA-ADM1-all/geoBoundaries-THA-ADM1.shp"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32647</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `geoBoundaries-THA-ADM1' from data source 
  `C:\kayc134\ISSS626_kayc\Take-Home_Ex\Take-Home_Ex01\data\geospatial\geoBoundaries-THA-ADM1-all\geoBoundaries-THA-ADM1.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 77 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 97.34381 ymin: 5.612851 xmax: 105.6368 ymax: 20.46483
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(adm1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'sf' and 'data.frame':  77 obs. of  6 variables:
 $ shapeName : chr  "Roi Et Province" "Phayao Province" "Nakhon Sawan Province" "Nong Bua Lam Phu Province" ...
 $ shapeISO  : chr  "TH-45" "TH-56" "TH-60" "TH-39" ...
 $ shapeID   : chr  "36821470B96343765829948" "36821470B12194119812739" "36821470B58837026258254" "36821470B48254980905782" ...
 $ shapeGroup: chr  "THA" "THA" "THA" "THA" ...
 $ shapeType : chr  "ADM1" "ADM1" "ADM1" "ADM1" ...
 $ geometry  :sfc_MULTIPOLYGON of length 77; first list element: List of 1
  ..$ :List of 1
  .. ..$ : num [1:1813, 1:2] 982599 983630 984362 984941 985133 ...
  ..- attr(*, "class")= chr [1:3] "XY" "MULTIPOLYGON" "sfg"
 - attr(*, "sf_column")= chr "geometry"
 - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA
  ..- attr(*, "names")= chr [1:5] "shapeName" "shapeISO" "shapeID" "shapeGroup" ...</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>adm1[[<span class="st">"shapeName"</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Roi Et Province"                   "Phayao Province"                  
 [3] "Nakhon Sawan Province"             "Nong Bua Lam Phu Province"        
 [5] "Chachoengsao Province"             "Surin Province"                   
 [7] "Nakhon Ratchasima Province"        "Sukhothai Province"               
 [9] "Phetchaburi Province"              "Chaiyaphum Province"              
[11] "Phetchabun Province"               "Surat Thani Province"             
[13] "Si Sa Ket Province"                "Nong Khai Province"               
[15] "Bangkok"                           "Khon Kaen Province"               
[17] "Loei Province"                     "Saraburi Province"                
[19] "Uthai Thani Province"              "Chumphon Province"                
[21] "Kalasin"                           "Phitsanulok Province"             
[23] "Ranong Province"                   "Udon Thani Province"              
[25] "Sakon Nakhon Province"             "Chiang Rai Province"              
[27] "Tak Province"                      "Nakhon Pathom Province"           
[29] "Lamphun Province"                  "Trat Province"                    
[31] "Ratchaburi Province"               "Yasothon Province"                
[33] "Phrae Province"                    "Yala Province"                    
[35] "Uttaradit Province"                "Buri Ram Province"                
[37] "Kamphaeng Phet Province"           "Lampang Province"                 
[39] "Nonthaburi Province"               "Bueng Kan Province"               
[41] "Narathiwat Province"               "Ubon Ratchathani Province"        
[43] "Prachuap Khiri Khan Province"      "Songkhla Province"                
[45] "Phuket Province"                   "Ang Thong Province"               
[47] "Maha Sarakham Province"            "Trang Province"                   
[49] "Suphan Buri Province"              "Sing Buri Province"               
[51] "Samut Songkhram Province"          "Rayong Province"                  
[53] "Prachin Buri Province"             "Phra Nakhon Si Ayutthaya Province"
[55] "Phichit Province"                  "Phatthalung Province"             
[57] "Phangnga Province"                 "Pattani Province"                 
[59] "Pathum Thani Province"             "Nakhon Si Thammarat Province"     
[61] "Nakhon Nayok Province"             "Mukdahan Province"                
[63] "Lopburi Province"                  "Krabi Province"                   
[65] "Chon Buri Province"                "Chiang Mai Province"              
[67] "Chai Nat Province"                 "Amnat Charoen Province"           
[69] "Samut Sakhon Province"             "Samut Prakan Province"            
[71] "Nan Province"                      "Chanthaburi Province"             
[73] "Nakhon Phanom Province"            "Kanchanaburi Province"            
[75] "Mae Hong Son Province"             "Sa Kaeo Province"                 
[77] "Satun Province"                   </code></pre>
</div>
</div>
</section>
<section id="filtering-to-bmr-boundary" class="level4">
<h4 class="anchored" data-anchor-id="filtering-to-bmr-boundary">4.1.2 Filtering to BMR boundary</h4>
<p>By obtaining the values in the province field, the BMR provinces could be filtered to derive the data set <code>bmr</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>bmr_provinces <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Bangkok"</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Nonthaburi Province"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Pathum Thani Province"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Samut Prakan Province"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Nakhon Pathom Province"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Samut Sakhon Province"</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>bmr <span class="ot">&lt;-</span> adm1 <span class="sc">%&gt;%</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(shapeName <span class="sc">%in%</span> bmr_provinces) <span class="sc">%&gt;%</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_make_valid</span>() <span class="sc">%&gt;%</span>             </span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_union</span>() <span class="sc">%&gt;%</span>                  </span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">crs =</span> <span class="fu">st_crs</span>(adm1)) <span class="sc">%&gt;%</span> </span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">name =</span> <span class="st">"Bangkok Greater Metropolitan Area"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="road-networks-in-bmr" class="level3">
<h3 class="anchored" data-anchor-id="road-networks-in-bmr">4.2 Road Networks in BMR</h3>
<section id="importing-road-network-data" class="level4">
<h4 class="anchored" data-anchor-id="importing-road-network-data">4.2.1 Importing road network data</h4>
<p>Similarly, the road networks data set was checked in order to correctly filter the required data. For the purpose of this analysis, we used only main roads.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>roads_raw <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/geospatial/thailand-260911-free.shp/gis_osm_roads_free_1.shp"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32647</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `gis_osm_roads_free_1' from data source 
  `C:\kayc134\ISSS626_kayc\Take-Home_Ex\Take-Home_Ex01\data\geospatial\thailand-260911-free.shp\gis_osm_roads_free_1.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 2928674 features and 10 fields
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: 97.31354 ymin: 5.643645 xmax: 105.6481 ymax: 20.47168
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(roads_raw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'sf' and 'data.frame':  2928674 obs. of  11 variables:
 $ osm_id  : chr  "4270622" "4828442" "4828443" "4828444" ...
 $ code    : int  5122 5122 5122 5122 5122 5122 5122 5122 5122 5153 ...
 $ fclass  : chr  "residential" "residential" "residential" "residential" ...
 $ name    : chr  "ถนนศิริมังคลาจารย์ ซอย1" "Soi Ruam- U-Thit" "Soi Ruam- U-Thit" NA ...
 $ ref     : chr  NA NA NA NA ...
 $ oneway  : chr  "B" "B" "B" "B" ...
 $ maxspeed: int  0 0 0 0 0 30 30 0 0 0 ...
 $ layer   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ bridge  : chr  "F" "F" "F" "F" ...
 $ tunnel  : chr  "F" "F" "F" "F" ...
 $ geometry:sfc_LINESTRING of length 2928674; first list element:  'XY' num [1:6, 1:2] 497127 497078 497058 496981 496928 ...
 - attr(*, "sf_column")= chr "geometry"
 - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA NA NA NA
  ..- attr(*, "names")= chr [1:10] "osm_id" "code" "fclass" "name" ...</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">unique</span>(roads_raw<span class="sc">$</span>fclass))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "bridleway"      "busway"         "cycleway"       "footway"       
 [5] "living_street"  "motorway"       "motorway_link"  "path"          
 [9] "pedestrian"     "primary"        "primary_link"   "residential"   
[13] "secondary"      "secondary_link" "service"        "steps"         
[17] "tertiary"       "tertiary_link"  "track"          "track_grade1"  
[21] "track_grade2"   "track_grade3"   "track_grade4"   "track_grade5"  
[25] "trunk"          "trunk_link"     "unclassified"   "unknown"       </code></pre>
</div>
</div>
</section>
<section id="filtering-to-main-road-classes" class="level4">
<h4 class="anchored" data-anchor-id="filtering-to-main-road-classes">4.2.2 Filtering to main road classes</h4>
<p>Based on the values in <code>fclass</code>, main roads (Kaart: Road Classifications Guide - OpenStreetMap Wiki, n.d.) were filtered out.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>main_road_classes <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"motorway"</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"motorway_link"</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"trunk"</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"trunk_link"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"primary"</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"primary_link"</span>,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"secondary"</span>,</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"secondary_link"</span>,</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"tertiary"</span>,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"tertiary_link"</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>roads_select <span class="ot">&lt;-</span> roads_raw <span class="sc">%&gt;%</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(fclass <span class="sc">%in%</span> main_road_classes)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="filtering-road-networks-to-bmr-boundary" class="level4">
<h4 class="anchored" data-anchor-id="filtering-road-networks-to-bmr-boundary">4.2.3 Filtering road networks to BMR boundary</h4>
<p>The road networks was filtered to the BMR boundary using <em>st_crop()</em> based on the boundary defined in <code>bmr</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>roads_bmr <span class="ot">&lt;-</span> roads_select <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_crop</span>(bmr) <span class="sc">%&gt;%</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_intersection</span>(bmr) <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_cast</span>(<span class="st">"MULTILINESTRING"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_cast</span>(<span class="st">"LINESTRING"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The boundary and road networks were plotted for a visual check.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(bmr) <span class="sc">+</span> <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"grey95"</span>) <span class="sc">+</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(roads_bmr) <span class="sc">+</span> <span class="fu">tm_lines</span>(<span class="at">col =</span> <span class="st">"steelblue"</span>, <span class="at">lwd =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="traffic-accidents-in-bmr" class="level3">
<h3 class="anchored" data-anchor-id="traffic-accidents-in-bmr">4.3 2022 Traffic Accidents in BMR</h3>
<section id="importing-traffic-accident-data-set" class="level4">
<h4 class="anchored" data-anchor-id="importing-traffic-accident-data-set">4.3.1 Importing traffic accident data set</h4>
<p>The traffic accident data was imported using <em>read_csv()</em>. As the study is confined to 2022 event points, the columns were checked to facilitate the filtering.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>accident_full <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/aspatial/thai_road_accident_2019_2022.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(accident_full)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 18
  acc_code incident_datetime   report_datetime     province_th province_en      
     &lt;dbl&gt; &lt;dttm&gt;              &lt;dttm&gt;              &lt;chr&gt;       &lt;chr&gt;            
1   571905 2019-01-01 00:00:00 2019-01-02 06:11:00 ลพบุรี        Loburi           
2  3790870 2019-01-01 00:03:00 2020-02-20 13:48:00 อุบลราชธานี   Ubon Ratchathani 
3   599075 2019-01-01 00:05:00 2019-01-01 10:35:00 ประจวบคีรีขันธ์ Prachuap Khiri K…
4   571924 2019-01-01 00:20:00 2019-01-02 05:12:00 เชียงใหม่     Chiang Mai       
5   599523 2019-01-01 00:25:00 2019-01-04 09:42:00 นครสวรรค์    Nakhon Sawan     
6   571982 2019-01-01 00:30:00 2019-01-07 12:46:00 แม่ฮ่องสอน    Mae Hong Son     
# ℹ 13 more variables: agency &lt;chr&gt;, route &lt;chr&gt;, vehicle_type &lt;chr&gt;,
#   presumed_cause &lt;chr&gt;, accident_type &lt;chr&gt;,
#   number_of_vehicles_involved &lt;dbl&gt;, number_of_fatalities &lt;dbl&gt;,
#   number_of_injuries &lt;dbl&gt;, weather_condition &lt;chr&gt;, latitude &lt;dbl&gt;,
#   longitude &lt;dbl&gt;, road_description &lt;chr&gt;, slope_description &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="filtering-accident-event-points-to-2022-and-bmr-boundary" class="level4">
<h4 class="anchored" data-anchor-id="filtering-accident-event-points-to-2022-and-bmr-boundary">4.3.2 Filtering accident event points to 2022 and BMR boundary</h4>
<p>After checking the columns and content, the required data for 2022 in BMR was filtered out as <code>accident_2022</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>bmr_province_names <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Bangkok"</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Nonthaburi"</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Pathum Thani"</span>,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Samut Prakan"</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Nakhon Pathom"</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Samut Sakhon"</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>accident_2022 <span class="ot">&lt;-</span> accident_full <span class="sc">%&gt;%</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">year</span>(incident_datetime) <span class="sc">==</span> <span class="dv">2022</span>,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    province_en <span class="sc">%in%</span> bmr_province_names</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="data-handling-for-point-events" class="level4">
<h4 class="anchored" data-anchor-id="data-handling-for-point-events">4.3.4 Data handling for point events</h4>
<p><strong>Missing Values</strong></p>
<p><em>summary()</em> was used to check for missing values. It was observed that there were 189 “NA” values in latitude and longtitude. These rows were dropped. Interestingly, there were accident records that had zero vehicles involved in the field <code>number_of_vehicles_involved</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(accident_2022)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    acc_code       incident_datetime             report_datetime              
 Min.   :5484851   Min.   :2022-01-01 01:00:00   Min.   :2022-01-02 02:43:00  
 1st Qu.:6445924   1st Qu.:2022-04-14 20:00:00   1st Qu.:2022-06-10 14:05:30  
 Median :6930875   Median :2022-07-26 09:30:00   Median :2022-09-16 10:51:00  
 Mean   :6891240   Mean   :2022-07-16 15:21:15   Mean   :2022-09-07 02:18:10  
 3rd Qu.:7513754   3rd Qu.:2022-10-19 08:43:45   3rd Qu.:2022-12-28 06:10:15  
 Max.   :7570954   Max.   :2022-12-31 23:11:00   Max.   :2023-01-26 09:49:00  
                                                                              
    province_th      province_en         agency           route     
 Length   :3782   Length   :3782   Length   :3782   Length   :3782  
 N.unique :   6   N.unique :   6   N.unique :   3   N.unique : 174  
 N.blank  :   0   N.blank  :   0   N.blank  :   0   N.blank  :   0  
 Min.nchar:   6   Min.nchar:   7   Min.nchar:  22   Min.nchar:   7  
 Max.nchar:  13   Max.nchar:  13   Max.nchar:  32   Max.nchar:  78  
                                                                    
                                                                    
    vehicle_type    presumed_cause   accident_type  number_of_vehicles_involved
 Length   :3782   Length   :3782   Length   :3782   Min.   : 0.00              
 N.unique :  12   N.unique :  30   N.unique :   9   1st Qu.: 1.00              
 N.blank  :   0   N.blank  :   0   N.blank  :   0   Median : 2.00              
 Min.nchar:   3   Min.nchar:   5   Min.nchar:   5   Mean   : 1.93              
 Max.nchar:  24   Max.nchar:  46   Max.nchar:  44   3rd Qu.: 2.00              
                                                    Max.   :10.00              
                                                                               
 number_of_fatalities number_of_injuries weather_condition    latitude    
 Min.   :0.00000      Min.   : 0.0000    Length   :3782    Min.   :13.45  
 1st Qu.:0.00000      1st Qu.: 0.0000    N.unique :   5    1st Qu.:13.66  
 Median :0.00000      Median : 0.0000    N.blank  :   0    Median :13.73  
 Mean   :0.04707      Mean   : 0.5714    Min.nchar:   4    Mean   :13.76  
 3rd Qu.:0.00000      3rd Qu.: 1.0000    Max.nchar:   5    3rd Qu.:13.84  
 Max.   :4.00000      Max.   :27.0000                      Max.   :14.25  
                                                           NAs    :189    
   longitude       road_description slope_description
 Min.   : 99.88   Length   :3782    Length   :3782   
 1st Qu.:100.45   N.unique :  13    N.unique :   3   
 Median :100.62   N.blank  :   0    N.blank  :   0   
 Mean   :100.58   Min.nchar:   5    Min.nchar:   5   
 3rd Qu.:100.71   Max.nchar:  36    Max.nchar:  10   
 Max.   :100.94                                      
 NAs    :189                                         </code></pre>
</div>
</div>
<p>Using <em>View()</em>, five records with zero vehicles involved were explored and these appeared to be data entry errors as the accident descriptions mentioned collisions. These five records were treated as data entry errors but retained, considering there would not be any analysis involving number of vehicles.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>accident_2022 <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(number_of_vehicles_involved <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">View</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Duplicate point events were checked for using the values in <code>acc_code</code>, which should be distinct for each traffic accident. There was no duplicate event identified.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(accident_2022)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3782</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>accident_dup <span class="ot">&lt;-</span> accident_2022 <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(acc_code, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(accident_dup)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3782</code></pre>
</div>
</div>
<p>The data set was transformed into an sf data set, while filtering out the 189 records that had missing latitude and longitude values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>accident_sf <span class="ot">&lt;-</span> accident_2022 <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(latitude), <span class="sc">!</span><span class="fu">is.na</span>(longitude)) <span class="sc">%&gt;%</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>), <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32647</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(accident_sf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3593</code></pre>
</div>
</div>
<p>The three data sets were plotted together for a visual check.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(bmr) <span class="sc">+</span> <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"grey95"</span>) <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(roads_bmr) <span class="sc">+</span> <span class="fu">tm_lines</span>(<span class="at">col =</span> <span class="st">"steelblue"</span>, <span class="at">lwd =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(accident_sf) <span class="sc">+</span> <span class="fu">tm_dots</span>(<span class="at">fill =</span> <span class="st">"red"</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="fl">0.02</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>An interactive map would allow for a more detailed exploration to ensure that event points fall neatly within the road networks.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The interactive map block is set to <em>eval: FALSE</em> to minimise computational overhead and reduce report rendering time.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"view"</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(bmr) <span class="sc">+</span> <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"grey95"</span>, <span class="at">fill_alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(roads_bmr) <span class="sc">+</span> <span class="fu">tm_lines</span>(<span class="at">col =</span> <span class="st">"steelblue"</span>, <span class="at">lwd =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(accident_sf) <span class="sc">+</span> <span class="fu">tm_dots</span>(<span class="at">fill =</span> <span class="st">"red"</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="fl">0.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="conversion-to-owin-and-ppp" class="level3">
<h3 class="anchored" data-anchor-id="conversion-to-owin-and-ppp">4.4 Conversion to owin and ppp</h3>
<p>The sf data set was converted to owin and ppp, which were required for SPPA. A check on the number of event points from <code>accident_sf</code> using <em>nrow()</em> was for comparison with event points after owin clipping.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(accident_sf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3593</code></pre>
</div>
</div>
<p>After owin clipping, there was a drop in four event points, from 3,593 to 3,589 This was a result of the accident event points outside the <code>bmr</code> boundary, even though they were labelled as BMR province in the data set. This handled the point events that fell outside the boundary.</p>
<p><em>rjitter()</em> from spadstat package was also used for point events of different traffic accidents that happened to overlap by moving them by 1 meter. Unlike <em>st_jitter</em>, the argument <em>retry = TRUE</em> in <em>rjitter()</em> addressed the possibility of a point event accidentally colliding with another after jittering. Based on the output, there was no point event that overlapped.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>bmr_owin <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(bmr)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>accident_ppp <span class="ot">&lt;-</span> <span class="fu">as.ppp</span>(accident_sf)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>accident_ppp_bmr <span class="ot">&lt;-</span> accident_ppp[bmr_owin]</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Overlap points detected:"</span>, <span class="fu">sum</span>(<span class="fu">duplicated</span>(accident_ppp_bmr)), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Overlap points detected: 0 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">any</span>(<span class="fu">duplicated</span>(accident_ppp_bmr))) {</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  accident_ppp_bmr <span class="ot">&lt;-</span> <span class="fu">rjitter</span>(</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    accident_ppp_bmr, </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">retry =</span> <span class="cn">TRUE</span>,   </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">nsim =</span> <span class="dv">1</span>, </span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">drop =</span> <span class="cn">TRUE</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Overlap points remaining after jittering:"</span>, <span class="fu">sum</span>(<span class="fu">duplicated</span>(accident_ppp_bmr)), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>accident_ppp_bmr</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern: 3589 points
Mark variables: 
   acc_code incident_datetime report_datetime province_th province_en agency 
route vehicle_type presumed_cause accident_type number_of_vehicles_involved 
number_of_fatalities number_of_injuries weather_condition road_description 
slope_description
window: polygonal boundary
enclosing rectangle: [587130.4, 712441.7] x [1484748.9, 1579087.2] units</code></pre>
</div>
</div>
<p><em>rescale.ppp()</em> was used to re-scaled to kilometers to make the statistical output more interpretable. This is particularly relevant for accident events, as using meters may result in an output of less than one accident.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>accident_ppp_km <span class="ot">&lt;-</span> <span class="fu">rescale.ppp</span>(accident_ppp_bmr, <span class="dv">1000</span>, <span class="st">"km"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="first-order-sppa" class="level2">
<h2 class="anchored" data-anchor-id="first-order-sppa">5. First-Order SPPA</h2>
<p>To examine the first-order spatial distribution of road traffic accidents in BMR, a planar Quadrat Analysis is conducted as a primary exploratory step. A network-based quadrat method segments the road network in order to aggregate point events along it (Shiode, 2008). However, it appears to be appropriate only for a smaller geometry boundary. Using the <em>quadratcount()</em> from spadstat.linnet package on the BMR road network resulted in about 250,000 line segments, which was computationally challenging to run as no output was produced even after more than 10 minutes (Baddeley et al., n.d.). Instead, a planar quadrat analysis was conducted to evaluate spatial variation and test for Complete Spatial Randomness (CSR) using a Chi-square goodness-of-fit test.</p>
<p>Complementing this, Network Kernel Density Estimation (NKDE) is applied. Traffic accidents are constrained to linear transport infrastructure rather than freely distributed across 2D space. NKDE adapts conventional density estimation by calculating accident intensity along network segments using shortest-path network distances rather than Euclidean distances (Okabe et al., 2009). Combining network-adjusted quadrat partitioning with NKDE prevents false density artifacts in planar spaces, offering a realistic representation of traffic accident risk along BMR’s road networks.</p>
<section id="quadrat-analysis" class="level3">
<h3 class="anchored" data-anchor-id="quadrat-analysis">5.1 Quadrat Analysis</h3>
<p><strong>Method Selection:</strong> Quadrat analysis was selected as an initial exploratory step because it provides two things the later methods do not, i.e., a significance test (Chi-square goodness-of-fit) that directly quantifies deviation from CSR with a p-value, and an explainable intensity surface that can be cross-checked against road length per cell to distinguish areas of accident concentration from areas that simply have more road exposure.</p>
<p>To detect non-random accident clustering across a road network, quadrat analysis divides the study area into a grid and compares observed cell counts against a Poisson distribution CSR using Chi-square.</p>
<p><strong>Parameter and Assumption:</strong> An 8×8 grid was used, balancing the ability to detect localised variation against the Chi-square test’s requirement that expected cell counts not be too small. As the BMR boundary is irregular, <em>st_intersection()</em> clipping means edge quadrats are genuinely smaller than interior ones. <em>intensity()</em> accounted for this using each quadrat’s actual clipped area. The test’s null hypothesis assumed a homogeneous Poisson process, where accidents occur independently and with equal probability anywhere in the study area.</p>
<section id="chi-square-quadrat-test" class="level4">
<h4 class="anchored" data-anchor-id="chi-square-quadrat-test">5.1.1 Chi-square quadrat test</h4>
<p>The <em>quadratcount()</em> from spadstat package was used to divid the study area into an 8 x 8 grid and count the number of accident point events in each cell.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>qcount <span class="ot">&lt;-</span> <span class="fu">quadratcount</span>(accident_ppp_km, <span class="at">nx =</span> <span class="dv">8</span>, <span class="at">ny =</span> <span class="dv">8</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>qcount_intensity <span class="ot">&lt;-</span> <span class="fu">intensity</span>(qcount)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="fu">quadrat.test</span>(accident_ppp_km, <span class="at">nx =</span> <span class="dv">8</span>, <span class="at">ny =</span> <span class="dv">8</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test of CSR using quadrat counts

data:  accident_ppp_km
X2 = 6223.5, df = 58, p-value &lt; 2.2e-16
alternative hypothesis: two.sided

Quadrats: 59 tiles (irregular windows)</code></pre>
</div>
</div>
<p>With a p-value of &lt; 0.05 from the chi-square quadrat test, the null hypothesis of CSR is rejected. This indicates that traffic accidents are not uniformly distributed across the BMR under a planar model, which is expected given that accidents are confined to a road network.</p>
</section>
<section id="plotting-accident-intensity" class="level4">
<h4 class="anchored" data-anchor-id="plotting-accident-intensity">5.1.2 Plotting Accident Intensity</h4>
<p>An 8×8 rectangular grid was generated over the BMR boundary and clipped to its irregular extent using <em>st_intersection()</em>, so quadrats along the study area’s edge reflect their true partial area. Accident counts per quadrat were obtained using <em>st_intersects()</em>, and intensity was calculated as accident count divided by each quadrat’s clipped area in km².</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>AI Use Disclosure
</div>
</div>
<div class="callout-body-container callout-body">
<p>AI tools were used to draft the R code for constructing the 8 × 8 quadrat grid over the BMR boundary and calculating accident intensity (accidents per km²) per quadrat. The output was reviewed and run by the author to verify correctness against the study data.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>accident_bmr <span class="ot">&lt;-</span> accident_sf <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_filter</span>(bmr, <span class="at">.predicate =</span> st_within)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>grid_bmr <span class="ot">&lt;-</span> <span class="fu">st_make_grid</span>(bmr, <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">8</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_sf</span>(<span class="at">quadrat_id =</span> <span class="fu">seq_along</span>(.), <span class="at">geometry =</span> .) <span class="sc">%&gt;%</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_intersection</span>(bmr)</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>grid_bmr <span class="ot">&lt;-</span> grid_bmr <span class="sc">%&gt;%</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">accident_count =</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(., accident_bmr)),</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">area_km2 =</span> <span class="fu">as.numeric</span>(<span class="fu">st_area</span>(.)) <span class="sc">/</span> <span class="fl">1e6</span>,</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">intensity =</span> accident_count <span class="sc">/</span> area_km2</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(grid_bmr) <span class="sc">+</span></span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(</span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"intensity"</span>,</span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill.scale =</span> <span class="fu">tm_scale_continuous</span>(<span class="at">values =</span> <span class="st">"viridis"</span>),</span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Accidents/km²"</span>,</span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a>                            <span class="at">text.size =</span> <span class="dv">1</span>, </span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a>                            <span class="at">width =</span> <span class="dv">6</span>)) <span class="sc">+</span></span>
<span id="cb43-23"><a href="#cb43-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(roads_bmr) <span class="sc">+</span> <span class="fu">tm_lines</span>(<span class="at">col =</span> <span class="st">"grey40"</span>, <span class="at">lwd =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb43-24"><a href="#cb43-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_title</span>(<span class="st">"Quadrat Intensity of Accidents (8×8 grid)"</span>) <span class="sc">+</span></span>
<span id="cb43-25"><a href="#cb43-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.title.size =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Quadrat intensity was plotted based on the 8 x 8 grid for visual inspection. There was a clear gradiant concentration in the bottom right, which seemed to coincide with the Bangkok province, peaking at 2.5 accidents/km² as represented by the yellow cell. The yellow cell however, appeared to have a higher than normal proportion of accidents considering that it did not have a very dense road network, as compared to the green cells.</p>
<p>An interactive map was plotted to check the infrastructures in the yellow cell.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The interactive map block is set to <em>eval: FALSE</em> to minimise computational overhead and reduce report rendering time.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"view"</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(grid_bmr) <span class="sc">+</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"intensity"</span>,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill_alpha =</span> <span class="fl">0.5</span>,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill.scale =</span> <span class="fu">tm_scale_continuous</span>(<span class="at">values =</span> <span class="st">"viridis"</span>),</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Accidents/km²"</span>,</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>                            <span class="at">text.size =</span> <span class="dv">1</span>,</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>                            <span class="at">width =</span> <span class="dv">6</span>)) <span class="sc">+</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(roads_bmr) <span class="sc">+</span> <span class="fu">tm_lines</span>(<span class="at">col =</span> <span class="st">"grey40"</span>, <span class="at">lwd =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_title</span>(<span class="st">"Quadrat Intensity of Accidents (8×8 grid)"</span>) <span class="sc">+</span></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.title.size =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><img src="images/clipboard-676313588.png" class="img-fluid" width="454"></p>
<p>From the interactive map, the Suvarnabhumi Airport could be seen in the yellow cell. This suggested that there was high traffic concentration despite the relatively shorter road length.</p>
<p>To verify the visual observation, road segments were clipped to each quadrat using <em>st_intersection()</em> and their lengths measured using <em>st_length()</em>. <em>group_by()</em> and <em>summarise(sum())</em> were then used to compute total road length per cell. Dividing accident count by road length would show how many accidents occur per kilometre of road, so cells with elevated risk could be told apart from cells that simply have a denser road network.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>AI Use Disclosure
</div>
</div>
<div class="callout-body-container callout-body">
<p>AI tools were used to draft the R code for clipping road segments to each quadrat and summing road length per cell. The output was reviewed and run by the author to verify correctness against the study data.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>road_lengths_by_quadrat <span class="ot">&lt;-</span> roads_bmr <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_intersection</span>(grid_bmr) <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">seg_length_km =</span> <span class="fu">as.numeric</span>(<span class="fu">st_length</span>(.)) <span class="sc">/</span> <span class="dv">1000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(quadrat_id) <span class="sc">%&gt;%</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">road_length_km =</span> <span class="fu">sum</span>(seg_length_km), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>grid_bmr <span class="ot">&lt;-</span> grid_bmr <span class="sc">%&gt;%</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">any_of</span>(<span class="fu">c</span>(<span class="st">"road_length_km"</span>, <span class="st">"accidents_per_km_road"</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(road_lengths_by_quadrat, <span class="at">by =</span> <span class="st">"quadrat_id"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">road_length_km =</span> <span class="fu">replace_na</span>(road_length_km, <span class="dv">0</span>),</span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">accidents_per_km_road =</span> accident_count <span class="sc">/</span> road_length_km</span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a>grid_bmr <span class="sc">%&gt;%</span></span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(intensity)) <span class="sc">%&gt;%</span></span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(quadrat_id, accident_count, area_km2, intensity, road_length_km, accidents_per_km_road) <span class="sc">%&gt;%</span></span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   quadrat_id accident_count area_km2 intensity road_length_km
1          23            557 184.7132 3.0154852       378.4973
2          22            325 184.7132 1.7594842       639.8052
3          30            320 184.7132 1.7324152       794.4529
4          24            168 105.7808 1.5881906       128.8788
5          21            222 184.7132 1.2018630       660.7764
6          39            197 184.7132 1.0665181       276.2152
7          12            196 184.7132 1.0611043       286.4515
8          47            180 184.7132 0.9744835       244.5642
9          29            179 184.7132 0.9690697       772.3341
10         31            153 184.7132 0.8283110       331.7613
   accidents_per_km_road
1              1.4716089
2              0.5079671
3              0.4027929
4              1.3035507
5              0.3359684
6              0.7132120
7              0.6842346
8              0.7360031
9              0.2317650
10             0.4611750</code></pre>
</div>
</div>
<p>Quadrats were ranked by intensity to identify the top 10 highest-accident-density cells. The table confirmed the visual observation that the yellow cell, i.e., quadrat_id 23, indeed had an unproportionate number of accidents compared to its road density, where there were 470 accidents for its 378km of roads. This was 1.24 accidents per km of road, compared to the next highest at 0.47 accidents.</p>
<p><strong>Interpretation:</strong> Together, these results provide consistent evidence against a planar CSR model. The Chi-square quadrat test rejects CSR (p &lt; 0.05), and the 8×8 intensity map identifies a specific area of concentration at the bottom right of BMR, i.e., quadrat 23, coinciding with Suvarnabhumi Airport. This concentration was not due to denser road networks. Quadrat 23 recorded the highest accident rate per kilometre of road (1.24) despite having a smaller road network than several neighbouring cells, indicating genuine excess risk rather than proportional exposure. As anticipated, however, planar quadrat analysis treated the entire study area as available space, which is not the case for a network-bound process. This limitation motivates the network-constrained NKDE analysis that follows, which estimates intensity only along the network itself.</p>
</section>
</section>
<section id="network-kernel-density-estimate-nkde" class="level3">
<h3 class="anchored" data-anchor-id="network-kernel-density-estimate-nkde">5.2 Network Kernel Density Estimate (NKDE)</h3>
<p><strong>Method Selection:</strong> NKDE was selected as it estimates density using shortest-path distances along the network rather than Euclidean distances across the 2D plane, directly addressing the network-bound nature of traffic accidents. Unlike planar KDE, it cannot mistake road network density for accident risk, since intensity is calculated only at locations where accidents can actually occur.</p>
<p><strong>Parameter and Assumption:</strong> A lixel length of 200m and minimum distance of 50m, following the standard example provided in the spNetwork package documentation (Gelb, 2025), were initially considered. However, given the substantially larger scale of the BMR network compared to the single-city network used in that reference example, a coarser lixel length of 400m and minimum distance of 200m was adopted instead as a practical trade-off between spatial resolution and tractability.</p>
<p>NKDE assumes the road network accurately represents where accidents can occur, and that bandwidth was appropriately sized to reveal genuine structure rather than noise or an over-smoothed trend. As roads outside the main-road classes were excluded from the network, accidents on minor roads were snapped to the nearest main-road segment during network construction, introducing some positional error at that scale.</p>
<section id="preparing-lixel-objects" class="level4">
<h4 class="anchored" data-anchor-id="preparing-lixel-objects">5.2.1 Preparing lixel objects</h4>
<p>Before NKDE could be computed, the road network was split into short, roughly equal-length segments called lixels. This provided a consistent spatial unit along the network at which density could be sampled. <em>method = “discontinuous”</em> was used, which corrects the bias present in the “simple” method, where an event’s mass is multiplied rather than divided at intersections (Sugihara et al., 2010). This produces an unbiased but discontinuous surface, adopted here over the smoother “continuous” method as a more computationally optimised choice.</p>
<p>As the BMR network is substantially larger than the package’s reference example (Gelb, 2025), spNetwork’s built-in strategies for large data sets were used.</p>
<ol type="a">
<li><p><em>grid_shape</em>, which partitions the study area into a grid (with a buffer to avoid edge effects at cell boundaries) so computation proceeds cell-by-cell rather than across the whole network at once.</p></li>
<li><p><em>agg = 5</em>, which aggregates events within a 5m radius before computing density, reducing the effective number of distinct points without materially affecting results at this resolution.</p></li>
<li><p><em>multisession()</em> from the future package was used to further optimise computation across available cores.</p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>lixels_bmr <span class="ot">&lt;-</span> <span class="fu">lixelize_lines</span>(roads_bmr, <span class="dv">400</span>, <span class="at">mindist =</span> <span class="dv">200</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>samples_bmr <span class="ot">&lt;-</span> <span class="fu">lines_center</span>(lixels_bmr)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>future<span class="sc">::</span><span class="fu">plan</span>(future<span class="sc">::</span><span class="fu">multisession</span>(<span class="at">workers =</span> <span class="dv">10</span>))  </span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>nkde_bmr <span class="ot">&lt;-</span> <span class="fu">nkde.mc</span>(</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">lines =</span> roads_bmr,</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">events =</span> accident_bmr,</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">w =</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(accident_bmr)),</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">samples =</span> samples_bmr,</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">kernel_name =</span> <span class="st">"quartic"</span>,</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">bw =</span> <span class="dv">500</span>,</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"discontinuous"</span>,</span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">div =</span> <span class="st">"bw"</span>,</span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">1</span>,</span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">tol =</span> <span class="dv">1</span>,</span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid_shape =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">10</span>),</span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">max_depth =</span> <span class="dv">8</span>,</span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">agg =</span> <span class="dv">5</span>,</span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">sparse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb48-21"><a href="#cb48-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">verbose =</span> <span class="cn">FALSE</span></span>
<span id="cb48-22"><a href="#cb48-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb48-23"><a href="#cb48-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-24"><a href="#cb48-24" aria-hidden="true" tabindex="-1"></a>future<span class="sc">::</span><span class="fu">plan</span>(future<span class="sc">::</span>sequential) </span>
<span id="cb48-25"><a href="#cb48-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-26"><a href="#cb48-26" aria-hidden="true" tabindex="-1"></a>samples_bmr<span class="sc">$</span>density <span class="ot">&lt;-</span> nkde_bmr</span>
<span id="cb48-27"><a href="#cb48-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-28"><a href="#cb48-28" aria-hidden="true" tabindex="-1"></a>samples_bmr_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(samples_bmr) <span class="sc">%&gt;%</span></span>
<span id="cb48-29"><a href="#cb48-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">density_scaled =</span> density <span class="sc">*</span> <span class="dv">1000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb48-30"><a href="#cb48-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(density_scaled)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="plotting-nkde" class="level4">
<h4 class="anchored" data-anchor-id="plotting-nkde">5.2.2 Plotting NKDE</h4>
<p>A fixed bandwidth of 500m was used, chosen because full data-driven bandwidth selection was too slow to run at BMR’s scale. Instead, 500m was obtained from the spNetwork package’s own bike-accident example (Gelb, 2025), where cross-validation found an optimal bandwidth of around 550 to 600m, and an adaptive-bandwidth approach found around 450 to 500m using the same discontinuous method used here. As this is a similar urban road-accident dataset, 500m offers a reasonable, evidence-informed estimate.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(bmr) <span class="sc">+</span> <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"grey95"</span>) <span class="sc">+</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(roads_bmr) <span class="sc">+</span> <span class="fu">tm_lines</span>(<span class="at">col =</span> <span class="st">"grey70"</span>, <span class="at">lwd =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(samples_bmr_sf) <span class="sc">+</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"density_scaled"</span>,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill.scale =</span> <span class="fu">tm_scale_intervals</span>(<span class="at">style =</span> <span class="st">"kmeans"</span>, <span class="at">n =</span> <span class="dv">7</span>, <span class="at">values =</span> <span class="fu">rev</span>(RColorBrewer<span class="sc">::</span><span class="fu">brewer.pal</span>(<span class="dv">7</span>, <span class="st">"Spectral"</span>))),</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"NKDE Density (×1000)"</span>),</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="fl">0.2</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title =</span> <span class="st">"Network KDE of Accidents"</span>,</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">main.title.size =</span> <span class="dv">1</span>,</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> The NKDE plot shows density concentrating heavily along a small number of specific roads, with the brightest red segments appearing along the same area surfaced in the quadrat analysis finding in Section 5.1.2. This road-based detail is a pattern the quadrat method could only capture at the resolution of an 8×8 grid, while NKDE was able to surface individual road segments, showing that risk is not spread across the general area but tied to specific stretches of road. The majority of the network remains at very low density (blue), including most of the western BMR, again consistent with the quadrat findings.</p>
</section>
</section>
</section>
<section id="second-order-sppa" class="level2">
<h2 class="anchored" data-anchor-id="second-order-sppa">6. Second-Order SPPA</h2>
<p>While the first-order SPPA evaluated large-scale variations in event intensity across the study area, the second-order analysis examined small-scale spatial interactions and distance dependencies between the accident events themselves. This was to determine whether road traffic accidents in the BMR exhibited significant spatial clustering, spatial dispersion or CSR across varying distance scales. The analysis tests whether the occurrence of a traffic accident at a specific location influences the probability of other accidents occurring nearby. To account for the physical constraints of transport infrastructure, both planar and network-constrained second-order functions—specifically Ripley’s K-function and its network equivalent—are evaluated against appropriate spatial null models.</p>
<section id="network-k-function-analysis" class="level3">
<h3 class="anchored" data-anchor-id="network-k-function-analysis">6.1 Network K-Function Analysis</h3>
<p><strong>Method Selection:</strong> Network K-function analysis was selected because the standard planar K-function’s assumption of an infinitely continuous 2D space, with distances measured as straight-line Euclidean distance, does not hold for traffic accidents, which are geocoded to and constrained by the road network. Under this constraint, the relevant question is not whether accidents deviate from randomness across the full plane, but whether they deviate from randomness within the network itself, with distances measured as shortest-path network distance rather than Euclidean distance (Yamada &amp; Thill, 2004). This directly extends the network-constrained reasoning already established for NKDE in Section 5.2, from a density surface to a formal test of spatial interaction between events.</p>
<p><strong>Parameter and Assumption:</strong> Monte Carlo simulation was used to empirically estimate the sampling distribution, comparing the observed K-function against 20 random realisations of points placed uniformly along the network rather than against an analytically derived benchmark. The test’s null hypothesis assumes CSR on the network, i.e.&nbsp;that accidents are equally likely to occur at any location along the road network and occur independently of one another. This differs from the planar CSR assumption used in Section 5.1, which treats the entire study area as available space; the network-constrained null model instead only requires deviation to be assessed relative to where accidents can actually occur.</p>
<p>Ho: The observed spatial point events (i.e., traffic accidents) are uniformly distributed over a street network in BMR.</p>
<p>A simulation count of <em>nsim = 19</em> was used for computational optimisation given the network’s size. This gives a minimum achievable p-value of 1/(nsim+1) = 0.05, enough to detect a clear rejection of network CSR, consistent with the strong clustering already found in Section 5.1. The trade-off is a coarser confidence envelope, estimated from only 19 simulated curves rather than a larger number, which limits precise interpretation if results fall close to the envelope boundary rather than clearly outside it.</p>
<section id="computing-the-network-k-function" class="level4">
<h4 class="anchored" data-anchor-id="computing-the-network-k-function">6.1.1 Computing the Network K-Function</h4>
<p><em>start = 0</em> and <em>end = 2000</em> were selected to test clustering at scales from the immediate network vicinity up to roughly four times the NKDE bandwidth (500m; Section 5.2.2), allowing comparison of whether clustering persists beyond the scale already revealed by density estimation, while remaining within a distance range still meaningful for targeted public-safety intervention. step and width were both set to 200m, giving 10 evenly-spaced distance bands across this range, a resolution fine enough to locate the approximate distance at which clustering becomes non-significant, without excessive computation time at metro scale.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">267</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>kfun_bmr <span class="ot">&lt;-</span> <span class="fu">kfunctions</span>(roads_bmr,</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>                        accident_bmr,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">start =</span> <span class="dv">0</span>,</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>                        <span class="at">end =</span> <span class="dv">2000</span>,</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">step =</span> <span class="dv">200</span>,</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>                        <span class="at">width =</span> <span class="dv">200</span>,</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>                        <span class="at">nsim =</span> <span class="dv">19</span>,</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>                        <span class="at">resolution =</span> <span class="dv">200</span>,</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>                        <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>kfun_bmr<span class="sc">$</span>plotk</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> The observed blue line sits definitively above the simulation envelope across the entire 0 to 2000m range tested. The null hypothesis is thus rejected. The blue line also steadily increases with distance, indicating that clustering compounds uniformly. This means accidents are far more clustered together than a network-random pattern would produce, and this holds at every distance scale.</p>
</section>
</section>
<section id="network-g-function" class="level3">
<h3 class="anchored" data-anchor-id="network-g-function">6.2 Network G-Function</h3>
<p><strong>Method Selection:</strong> While the K-function is cumulative, summing all event pairs within a given distance, the G-function instead uses nearest-neighbour distances, making it sensitive to local clustering e.g., accidents occurring very close to one another, such as at a single junction. Running both K- and G-functions provides a check on each other. If the G-function shows strong short-range clustering while the K-function’s signal is concentrated at similarly small distances, this corroborates a genuinely local hotspot effect rather than a broader network-level pattern that only appears clustered when aggregated cumulatively.</p>
<p><strong>Parameter and Assumption:</strong> As the K- and G-functions are computed together in a single <em>kfunctions()</em> call, the same parameters and assumptions described in Section 6.1 apply here.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>kfun_bmr<span class="sc">$</span>plotg</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> The observed blue line sits definitively above the simulated envelope, across the entire 0 to 2000m range tested. The null hypothesis is thus rejected. The gap between the line and envelope is slightly higher below 500m distance, with a sharp spike slightly below 250m. This indicates that accidents happen below 500m of another accident far more often, particularly at about 250m.</p>
<p>Both K- and G-functions corroborates, and substantially strengthens, the first-order findings from quadrat analysis and NKDE. Accidents in the BMR are not merely following where roads are, or even where roads are especially dense, but are genuinely clustering at every scale examined, particularly at distances below 500m, particularly at about 250m.</p>
</section>
</section>
<section id="value-added-analysis" class="level2">
<h2 class="anchored" data-anchor-id="value-added-analysis">7. Value-Added Analysis</h2>
<p>The first- and second-order analysis established that accidents in the BMR cluster significantly beyond what network geometry alone would predict, with the strongest signal concentrated in quadrat 23, where Suvarnabhumi Airport is located. This section extends these findings using two methods to addresss two questions the first- and second-order analyses could not answer on their own:</p>
<ol type="a">
<li>Is quadrat 23’s extreme accident rate a statistically significant spatial outlier relative to its immediate surroundings, or does it simply reflect the same local variation expected by chance.</li>
<li>Do the most severe accidents cluster in the same locations as accidents overall, or do they exhibit a distinct spatial pattern.</li>
</ol>
<p>Both questions carry direct implications for how the public-safety planning recommendations in Section 8 should be scoped and targeted.</p>
<section id="local-morans-i" class="level3">
<h3 class="anchored" data-anchor-id="local-morans-i">7.1 Local Moran’s I</h3>
<p><strong>Method Selection:</strong> Local Indicators of Spatial Association (LISA), specifically Local Moran’s I, classify each spatial unit into one of four categories based on its own value relative to its neighbours: High-High and Low-Low (i.e., a value similar to its surrounding neighbourhood, forming part of a genuine cluster), and High-Low and Low-High (i.e., a value markedly different from its neighbours, indicating a spatial outlier). This is selected because it directly tests whether Quadrat 23’s elevated accident rate reflects a broader areal cluster consistent with the road-network-wide clustering found in Section 6, or a localised outlier relative to its immediate surroundings. This is a distinction the point-pattern methods in Sections 5 and 6 could not resolve on their own, since they either treat the whole network as one continuous space (K/G-functions) or measure exposure without reference to neighbouring areas (Section 5.1.2’s road-length comparison).</p>
<p><strong>Parameter and Assumption:</strong> Queen contiguity is used to define neighbours using <em>st_contiguity()</em>, with row-standardised weights <em>style = “W”</em>. A simulation count of nsim = 999 is used. The method assumes the spatial weights matrix appropriately represents meaningful spatial relationships between quadrats, where edge quadrats with fewer neighbours, as noted in Section 5.1, may yield less stable local estimates than interior quadrats.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sfdep)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>wm_q <span class="ot">&lt;-</span> grid_bmr <span class="sc">%&gt;%</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> <span class="fu">st_contiguity</span>(geometry),</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">wt =</span> <span class="fu">st_weights</span>(</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>          nb, <span class="at">style =</span> <span class="st">"W"</span>),</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>)</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wm_q<span class="sc">$</span>nb)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 59 
Number of nonzero links: 368 
Percentage nonzero weights: 10.57167 
Average number of links: 6.237288 
Link number distribution:

 3  5  7  8 
10 16  6 27 
10 least connected regions:
1 7 15 23 31 47 55 56 57 59 with 3 links
27 most connected regions:
9 10 11 12 13 17 18 19 20 21 25 26 27 28 29 33 34 35 36 37 40 41 42 43 44 45 53 with 8 links</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">267</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>lisa <span class="ot">&lt;-</span> wm_q <span class="sc">%&gt;%</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">local_moran =</span> <span class="fu">local_moran</span>(</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>    intensity, nb, wt, <span class="at">nsim =</span> <span class="dv">999</span>),</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">.before =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(local_moran)</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>lisa <span class="sc">%&gt;%</span></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(quadrat_id <span class="sc">==</span> <span class="dv">23</span>) <span class="sc">%&gt;%</span></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(quadrat_id, ii, p_ii, mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  quadrat_id    ii      p_ii mean     
       &lt;int&gt; &lt;dbl&gt;     &lt;dbl&gt; &lt;fct&gt;    
1         23  5.00 0.0000452 High-High</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>ii.map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">fill =</span> <span class="st">"ii"</span>,</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill.scale =</span> <span class="fu">tm_scale_intervals</span>(</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">style =</span> <span class="st">"pretty"</span>,</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">n =</span> <span class="dv">5</span>,</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">values =</span> <span class="st">"brewer.RdBu"</span>),</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill.legend =</span> <span class="fu">tm_legend</span>(</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">title =</span> <span class="st">"Local Moran's I"</span>,</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">position =</span> <span class="fu">tm_pos_out</span>())) <span class="sc">+</span></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">fill_alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_title</span>(<span class="st">"Local Moran's I"</span>)</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a>p_ii.map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">fill =</span> <span class="st">"p_ii"</span>,</span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill.scale =</span> <span class="fu">tm_scale_intervals</span>(</span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a>                <span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="fl">0.1</span>, <span class="cn">Inf</span>),</span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a>                <span class="at">values =</span> <span class="st">"-brewer.Reds"</span>),</span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill.legend =</span> <span class="fu">tm_legend</span>(</span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a>                <span class="at">title =</span> <span class="st">"p-value"</span>,</span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a>                <span class="at">position =</span> <span class="fu">tm_pos_out</span>()</span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a>              )) <span class="sc">+</span></span>
<span id="cb58-22"><a href="#cb58-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">fill_alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb58-23"><a href="#cb58-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_title</span>(<span class="st">"p-values of Local Moran's I"</span>)</span>
<span id="cb58-24"><a href="#cb58-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-25"><a href="#cb58-25" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(ii.map, p_ii.map, <span class="at">asp =</span> <span class="dv">1</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> Local Moran’s I identifies a large, statistically significant High-High cluster spanning 9 contiguous quadrats across the central to southern-eastern BMR, including quadrat 23 (ii = 5.00, p &lt; 0.05).</p>
<p>This corroborates the network K/G-function findings in Section 6, that clustering is not confined to a single point but extends across a wider area, consistent with the K-function’s distance-independent result. It also adds a distinction the earlier road-length comparison in Section 5.1.2 could not make on its own. Rather than being a High-Low outlier standing apart from its surroundings, quadrat 23 sits within a broader region of similarly elevated risk. Its disproportionate accident rate relative to road length remains real, but occurs within, not despite, this wider cluster.</p>
<p>Together, the three analyses point to the same conclusion at increasing spatial resolution. Accidents concentrate in a specific area (Section 5.1), cluster with one another at every distance tested (Section 6), and form a genuine multi-quadrat cluster rather than an isolated anomaly (Section 7.1). This supports an area-wide intervention across the identified cluster, rather than one scoped to quadrat 23 alone.</p>
</section>
<section id="network-cross-kg-function-fatal-vs-non-fatal-accidents" class="level3">
<h3 class="anchored" data-anchor-id="network-cross-kg-function-fatal-vs-non-fatal-accidents">7.2 Network Cross-K/G Function: Fatal vs Non-Fatal Accidents</h3>
<p><strong>Method Selection:</strong> The network K/G-function analysis in Section 6 treated all accidents as a single, undifferentiated point pattern. This section extends that analysis using spNetwork’s bivariate cross-K/G function, which tests whether two distinct point types, i.e., fatal and non-fatal accidents, are spatially associated with one another along the network, beyond what their individual frequencies alone would predict. This was not covered in the core exercise and directly extends the network-constrained second-order framework already established in Section 6. This addresses a materially different and more policy-relevant question on whether the most severe accidents cluster in the same locations.</p>
<p><strong>Parameter and Assumption:</strong> Accidents are split into two groups using number_of_fatalities &gt; 0, using a binary treatment, since fatalities are a rare and heavily zero-inflated outcome. The same network <code>roads_bmr</code>, distance range (start = 0, end = 2000), and resolution settings used in Section 6.1 are retained for direct comparability between the univariate and bivariate results. Given the substantially smaller number of fatal accidents relative to non-fatal accidents, nsim = 19 is used for the same computational reasons as Section 6.1. The null hypothesis assumes that, given the fixed locations of non-fatal accidents on the network, fatal accidents are randomly and independently distributed.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>AI Use Disclosure
</div>
</div>
<div class="callout-body-container callout-body">
<p>AI tools were used to draft the R code for classifying accidents into fatal and non-fatal groups (based on <code>number_of_fatalities</code>). The output was reviewed and run by the author to verify correctness against the study data.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>accident_bmr <span class="ot">&lt;-</span> accident_bmr <span class="sc">%&gt;%</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fatal =</span> <span class="fu">if_else</span>(number_of_fatalities <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="st">"Fatal"</span>, <span class="st">"Non-fatal"</span>))</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>accident_fatal <span class="ot">&lt;-</span> accident_bmr <span class="sc">%&gt;%</span> <span class="fu">filter</span>(fatal <span class="sc">==</span> <span class="st">"Fatal"</span>)</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>accident_nonfatal <span class="ot">&lt;-</span> accident_bmr <span class="sc">%&gt;%</span> <span class="fu">filter</span>(fatal <span class="sc">==</span> <span class="st">"Non-fatal"</span>)</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(accident_fatal)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 158</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(accident_nonfatal)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3431</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">267</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>cross_kfun <span class="ot">&lt;-</span> <span class="fu">cross_kfunctions</span>(roads_bmr,</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>                                accident_fatal,</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>                                accident_nonfatal,</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>                                <span class="at">start =</span> <span class="dv">0</span>,</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>                                <span class="at">end =</span> <span class="dv">2000</span>,</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>                                <span class="at">step =</span> <span class="dv">200</span>,</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>                                <span class="at">width =</span> <span class="dv">200</span>,</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>                                <span class="at">nsim =</span> <span class="dv">19</span>,</span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>                                <span class="at">resolution =</span> <span class="dv">200</span>,</span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a>                                <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>cross_kfun<span class="sc">$</span>plotk</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>cross_kfun<span class="sc">$</span>plotg</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> Both the cross-K and cross-G functions reject spatial independence between fatal and non-fatal accidents, with observed values remaining above the simulation envelope across the entire 0 to 2,000m range. Fatal accidents consistently occur closer to non-fatal accidents than random co-location would predict, most strongly at short range, as observed in the cross-G function’s early peak at about 250m, which shows fatal accidents frequently have a non-fatal accident as an immediate nearest neighbour.</p>
<p>This means the hotspot area is not just where accidents are frequent, but where severe and less-severe accidents occur alongside each other.</p>
</section>
</section>
<section id="public-safety-planning-and-management-implications" class="level2">
<h2 class="anchored" data-anchor-id="public-safety-planning-and-management-implications">8. Public-Safety Planning and Management Implications</h2>
<section id="summary-of-analysis" class="level3">
<h3 class="anchored" data-anchor-id="summary-of-analysis">8.1 Summary of Analysis</h3>
<p>The analyses in Sections 5 to 7 converge on a consistent finding. Road traffic accidents in the BMR are not randomly distributed, nor do they simply follow road network density. Quadrat analysis (Section 5.1) identified a specific area of concentration, i.e., quadrat 23 where Suvarnabhumi Airport, with an accident rate per kilometre of road roughly 2.6 times higher than the next-highest quadrat. This indicated a disproportion road exposure alone cannot explain. NKDE (Section 5.2) resolved this concentration to specific networks rather than the whole area. Network K/G-functions (Section 6) confirmed accidents cluster with one another at every distance tested up to 2km, and Local Moran’s I (Section 7.1) confirmed this is a genuine multi-quadrat cluster, not an isolated anomaly. The cross-K/G analysis (Section 7.2) further showed fatal accidents are not spatially separate from this pattern, as they occur consistently near non-fatal accidents, most strongly at short range.</p>
<p>A specific corridor spanning several contiguous quadrats around quadrat, plausibly associated with Suvarnabhumi Airport access infrastructure, is a genuine statistical concentration of both accident frequency and severity, not an artefact of road density or chance.</p>
</section>
<section id="reccommendations" class="level3">
<h3 class="anchored" data-anchor-id="reccommendations">8.2 Reccommendations</h3>
<p><strong>Emergency response and resource allocation:</strong> Given the confirmed cluster’s spatial extent (Section 7.1) rather than a single point, pre-positioning ambulance or traffic-police resources across the identified network is directly supported by the evidence. The fatal/non-fatal co-clustering finding (Section 7.2) further supports treating this network as a priority for reducing response time specifically, since severe outcomes are concentrated exactly where accident volume is highest. However, selecting the specific road segments or stations for resource pre-positioning would require additional information not present in this dataset, such as real-time traffic congestion patterns, peak-hour travel times and existing response-unit coverage.</p>
<p><strong>Road-safety and infrastructure planning:</strong> Quadrant 23’s disproportionate accident rate relative to its road length (Section 5.1.2), smaller network, higher rate, suggests engineering review, i.e., signage, speed enforcement, intersection design, is warranted there specifically, ahead of areas with more road-km but proportionally fewer accidents. This is a reasonable planning priority, but not evidence that any specific design flaw causes the pattern, which would require site-level engineering assessment beyond this data set.</p>
<p><strong>Resource allocation across the BMR.</strong> The cold spot in the north-western BMR indicates comparatively lower accident-related demand there. This can inform relative prioritisation of accident-focused resources, though it should not be read as evidence of lower risk per unit of exposure, e.g., per vehicle-km, which this analysis does not measure.</p>
<p><em>Required additional information:</em> the specific causal mechanism behind the corridor’s excess risk, e.g., airport-related traffic conflict, road geometry and driver behaviour, is not identified by this analysis and would require site-level investigation. Land-use and long-term infrastructure planning decisions would need traffic volume and exposure data this study does not include. This study also does not claim that the identified provinces or roads are inherently more dangerous per unit of traffic, only that raw and network-adjusted accident concentration is elevated there in 2022.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>AI Use Disclosure
</div>
</div>
<div class="callout-body-container callout-body">
<p>AI tools were used to provide language assistance during the preparation of this report. AI support was limited to improving the clarity, structure and fluency of written content, including refinement of sentence construction, grammar and academic writing style. All analysis, interpretations, conclusions, insights, hypotheses, business recommendations and managerial implications presented in this report were independently developed by the author based on the dataset, statistical outputs and domain knowledge. AI did not generate the underlying analytical findings or determine the conclusions reached in this study.</p>
</div>
</div>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Baddeley, A., Turner, R., &amp; Rubak, E. (n.d.). quadratcount: Quadrat counting for a point pattern on a linear network. Rdocumentation. https://www.rdocumentation.org/packages/spatstat.linnet/versions/3.5-0/topics/quadratcount</p>
<p>Download OpenStreetMap for Thailand | Geofabrik Download Server. (n.d.). Geofabrik Download Server. https://download.geofabrik.de/asia/thailand.html</p>
<p>Gelb, J. (2025, October 4). Network Kernel Density Estimate. https://cran.r-project.org/web/packages/spNetwork/vignettes/NKDE.html</p>
<p>Kaart: Road Classifications Guide - OpenStreetMap Wiki. (n.d.). https://wiki.openstreetmap.org/wiki/Kaart:_Road_Classifications_Guide</p>
<p>Kam, T. S. R for Geospatial Data Science and Analytics. https://r4gdsa.netlify.app/</p>
<p>Klokan Technologies GmbH. (n.d.). EPSG.io: Coordinate Systems worldwide. https://epsg.io/</p>
<p>McSwiggan, G. &amp; Department of Mathematics and Statistics, UWA. (2019). Spatial point process methods for linear networks with applications to road accident analysis. https://api.research-repository.uwa.edu.au/ws/portalfiles/portal/81039500/THESIS_DOCTOR_OF_PHILOSOPHY_MCSWIGGAN_Gregory_Edward_2020.pdf</p>
<p>Okabe, A., Satoh, T., Sugihara, K.: A kernel density estimation method for networks, its computational method and a GIS-based tool. International Journal of Geographical Information Science 23, 7–32 (2009)</p>
<p>Okabe, A., &amp; Yamada, I. (2001). The K-function method on a network and its computational implementation. Geographical Analysis, 33(3), 271–290.</p>
<p>R, T. (2023). Thailand Road Accident [2019-2022]. Kaggle. https://www.kaggle.com/datasets/thaweewatboy/thailand-road-accident-2019-2022</p>
<p>Runfola D, Anderson A, Baier H, Crittenden M, Dowker E, Fuhrig S, et al.&nbsp;(2020) geoBoundaries: A global database of political administrative boundaries. PLoS ONE 15(4): e0231866. https://doi.org/10.1371/journal.pone.0231866.</p>
<p>Shiode, S. (2008). Analysis of a distribution of point events using the Network‐Based Quadrat Method. Geographical Analysis, 40(4), 380–400. https://doi.org/10.1111/j.0016-7363.2008.00735.x</p>
<p>Sugihara, K., Satoh, T., &amp; Okabe, A. (2010). Simple and unbiased kernel function for network analysis. 2010 10th International Symposium on Communications and Information Technologies, 827–832. IEEE.</p>
<p>Yamada, I., &amp; Thill, J.-C. (2004, June). Comparison of planar and network K-functions in traffic accident analysis. ScienceDirect. https://www.sciencedirect.com/science/article/abs/pii/S0966692303000619</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>