{
  "hash": "1571e9fd98a2e11e5bcc77cf065f29f9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"01a: Geospatial Data Science with R\"\nauthor: \"Chia Ka Ying\"\ndate: \"2026-08-15\"\ndate-modified: \"2026-08-26\"\n---\n\nGeospatial data science is a process of importing, wrangling, integrating, and processing geographically referenced data sets. In this hands-on exercise, I will perform geospatial data science tasks in R by using sf package.\n\n## 1. Getting Started: Loading R Packages\n\nUsing the *p_load* function of pacman package, I will load sf and tidyverse R packages into the R environment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, tidyverse)\n```\n:::\n\n\n## 2. Importing Geospatial Data\n\nUsing the *st_read()* of sf package, I will be loading the following three geospatial data and converting them to the desired formats:\n\n- `MP14_SUBZONE_NO_SEA_PL`, a polygon feature layer in GeoJSON format, which will be converted to an ESRI shapefile format;\n\n- `PreSchoolsLocation`, point feature layer in GeoJSON format, which will be converted to a KML file format; and\n\n- `CyclingPath`, a line feature layer in ESRI shapefile format.\n\n### 2.1 Importing polygon feature data and coverting to shapefile format (MP14_SUBZONE_NO_SEA_PL)\n\nUsing the *st_read()* function of sf package, I will be importing the polygon feature layer in **GeoJSON** format file `MP14_SUBZONE_WEB_PL` into R. I will also be converting it from a **GeoJSON** format to an **ESRI shapefile** format using the *st_write()* function. To ensure that any existing file is not overwritten, I have included a *delete_dsn = FALSE* argument and *#\\| eval: false* chunk option to display the code in the final rendered code but prevents RStudio from executing it during the rendering process to prevent an error.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz <- st_read(\"data/geospatial/MP14_SUBZONE_NO_SEA_PL.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `MP14_SUBZONE_NO_SEA_PL' from data source \n  `C:\\kayc134\\ISSS626_kayc\\Hands-on_Ex\\Hands-on_Ex01\\data\\geospatial\\MP14_SUBZONE_NO_SEA_PL.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 323 features and 13 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 103.6057 ymin: 1.158699 xmax: 104.0885 ymax: 1.470775\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndir.create(\"data/geospatial/mpsz\", recursive = TRUE, showWarnings = FALSE) #create folder\n\nst_write(mpsz, \"data/geospatial/mpsz/MP14_SUBZONE_NO_SEA_PL.shp\", \n         driver = \"ESRI Shapefile\", delete_dsn = FALSE) #write files in ESRI format and prevent overwrite\n```\n:::\n\n\nThe message above reveals that the geospatial objects are multipolygon features. There are a total of 323 multipolygon features and 13 fields in `mpsz` simple feature data frame. `mpsz` is in **WGS 84**, which is a geodetic system and thusgeographic (3D/spherical) rather than projected (2D/flat). The bounding box provides the x extend and y extend of the data.\n\n### 2.2 Importing point feature layer and coverting to KML format (PreSchoolsLocation)\n\nSimilary, using the *st_read()* function of sf package, I will be importing the point feature layer in **GeoJSON** format file `PreSchoolsLocation` into R. I will also be converting it from a **GeoJSON** format to **KML** format using the *st_write()* function. To ensure that any existing file is not overwritten, I have included a *delete_dsn = FALSE* argument and *#\\| eval: false* chunk option to display the code in the final rendered code but prevents RStudio from executing it during the rendering process to prevent an error.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreschool <- st_read(\"data/geospatial/PreSchoolsLocation.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PreSchoolsLocation' from data source \n  `C:\\kayc134\\ISSS626_kayc\\Hands-on_Ex\\Hands-on_Ex01\\data\\geospatial\\PreSchoolsLocation.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 2290 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndir.create(\"data/geospatial/preschool\", recursive = TRUE, showWarnings = FALSE) #create folder\n\nst_write(preschool, \"data/geospatial/preschool/preschool.kml\", \n         driver = \"KML\", delete_dsn = FALSE) #write files in KML format and prevent overwrite\n```\n:::\n\n\nThe message above reveals that `preschool` is a point feature data frame. There are a total of 2290 features and 2 fields. `preschool` is in **WGS 84**, which is the same as `mpsz`.\n\n### 2.3 Importing polyline feature data in shapefile format (CyclingPath)\n\nThe code chunk below uses *st_read()* function of sf package to import CyclingPath shapefile into R as a line feature data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncyclingpath = st_read(dsn = \"data/geospatial/CyclingPath\", \n                         layer = \"CyclingPath\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `CyclingPath' from data source \n  `C:\\kayc134\\ISSS626_kayc\\Hands-on_Ex\\Hands-on_Ex01\\data\\geospatial\\CyclingPath' \n  using driver `ESRI Shapefile'\nSimple feature collection with 4830 features and 7 fields\nGeometry type: MULTILINESTRING\nDimension:     XY\nBounding box:  xmin: 11721.1 ymin: 27550.13 xmax: 42809.37 ymax: 49702.59\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\nThere are a total of 4830 features and 7 fields in cyclingpath sf data frame. The geospatial entities are capture in multilinestring object. Unlike the earlier two data sets, this data set is in **SVY21** projected coordinates system.\n\n## 3. Checking the Content of a Simple Feature Data Frame\n\nBefore performing data wrangling, I will be learning more about the `mpsz` data set using *st_geometry(),* *glimpse()* and *head().*\n\n### 3.1 Working with st_geometry\n\nTo retrieve the geometry list-column, I will be using the below code chunk, which is the more general way, rather than *mpsz\\$geom* or *mpsz\\[\\[1\\]\\]*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_geometry(mpsz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeometry set for 323 features \nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 103.6057 ymin: 1.158699 xmax: 104.0885 ymax: 1.470775\nGeodetic CRS:  WGS 84\nFirst 5 geometries:\n```\n\n\n:::\n:::\n\n\n### 3.2 Working with glimpse() and Date Conversion\n\nBeside the basic geospatial feature information, I would also like to learn more about the associated attribute information in the data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(mpsz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 323\nColumns: 14\n$ OBJECTID_1   <int> 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 3…\n$ SUBZONE_NO   <int> 2, 2, 3, 4, 5, 4, 10, 12, 4, 6, 1, 1, 3, 8, 3, 7, 9, 2, 1…\n$ SUBZONE_N    <chr> \"PEOPLE'S PARK\", \"BUKIT MERAH\", \"CHINATOWN\", \"PHILLIP\", \"…\n$ SUBZONE_C    <chr> \"OTSZ02\", \"BMSZ02\", \"OTSZ03\", \"DTSZ04\", \"DTSZ05\", \"OTSZ04…\n$ CA_IND       <chr> \"Y\", \"N\", \"Y\", \"Y\", \"Y\", \"Y\", \"N\", \"Y\", \"N\", \"Y\", \"Y\", \"Y…\n$ PLN_AREA_N   <chr> \"OUTRAM\", \"BUKIT MERAH\", \"OUTRAM\", \"DOWNTOWN CORE\", \"DOWN…\n$ PLN_AREA_C   <chr> \"OT\", \"BM\", \"OT\", \"DT\", \"DT\", \"OT\", \"BM\", \"DT\", \"BM\", \"DT…\n$ REGION_N     <chr> \"CENTRAL REGION\", \"CENTRAL REGION\", \"CENTRAL REGION\", \"CE…\n$ REGION_C     <chr> \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR…\n$ INC_CRC      <chr> \"B4120D23006C932A\", \"1C51019439A68700\", \"0FF1661344C84AED…\n$ FMEL_UPD_D   <chr> \"20160511160621\", \"20160511160621\", \"20160511160621\", \"20…\n$ SHAPE_1.AREA <dbl> 93140.44, 411722.82, 587222.68, 39437.94, 188767.49, 1330…\n$ SHAPE_1.LEN  <dbl> 1822.1927, 3074.9632, 4297.5999, 871.5549, 1872.7522, 160…\n$ geometry     <MULTIPOLYGON [°]> MULTIPOLYGON (((103.8432 1...., MULTIPOLYGON…\n```\n\n\n:::\n:::\n\n\nThe *glimpse()* report reveals the data type of each fields. For example, `SUBZONE_NO` is in integer data type, `SUBZONE_N`, `CA_IND`, `PLN_AREA_N` and `REGION_N` fields are in character data type, and `SHAPE_1.AREA` and `SHAPE_1.LEN` fields are in double-precision values.\n\nIt should be noted that `FMEL_UPD_D` is showing as a 14-digit character rather than a date type. The 14 digits should be referring to the year, month, date, hour, minute and second in a \"YYYYMMDDHHMMSS\" format and will need to be converted using *ymd_hms()* within a *mutate()* function, which is part of the tidyverse package. I also dropped the time using *as_date()*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz <- mpsz %>%\n  mutate(FMEL_UPD_D = as_date(ymd_hms (FMEL_UPD_D))) #convert to date and drops the time\n\nglimpse(mpsz) #verify that it has been converted to date\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 323\nColumns: 14\n$ OBJECTID_1   <int> 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 3…\n$ SUBZONE_NO   <int> 2, 2, 3, 4, 5, 4, 10, 12, 4, 6, 1, 1, 3, 8, 3, 7, 9, 2, 1…\n$ SUBZONE_N    <chr> \"PEOPLE'S PARK\", \"BUKIT MERAH\", \"CHINATOWN\", \"PHILLIP\", \"…\n$ SUBZONE_C    <chr> \"OTSZ02\", \"BMSZ02\", \"OTSZ03\", \"DTSZ04\", \"DTSZ05\", \"OTSZ04…\n$ CA_IND       <chr> \"Y\", \"N\", \"Y\", \"Y\", \"Y\", \"Y\", \"N\", \"Y\", \"N\", \"Y\", \"Y\", \"Y…\n$ PLN_AREA_N   <chr> \"OUTRAM\", \"BUKIT MERAH\", \"OUTRAM\", \"DOWNTOWN CORE\", \"DOWN…\n$ PLN_AREA_C   <chr> \"OT\", \"BM\", \"OT\", \"DT\", \"DT\", \"OT\", \"BM\", \"DT\", \"BM\", \"DT…\n$ REGION_N     <chr> \"CENTRAL REGION\", \"CENTRAL REGION\", \"CENTRAL REGION\", \"CE…\n$ REGION_C     <chr> \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR\", \"CR…\n$ INC_CRC      <chr> \"B4120D23006C932A\", \"1C51019439A68700\", \"0FF1661344C84AED…\n$ FMEL_UPD_D   <date> 2016-05-11, 2016-05-11, 2016-05-11, 2016-05-11, 2016-05-…\n$ SHAPE_1.AREA <dbl> 93140.44, 411722.82, 587222.68, 39437.94, 188767.49, 1330…\n$ SHAPE_1.LEN  <dbl> 1822.1927, 3074.9632, 4297.5999, 871.5549, 1872.7522, 160…\n$ geometry     <MULTIPOLYGON [°]> MULTIPOLYGON (((103.8432 1...., MULTIPOLYGON…\n```\n\n\n:::\n:::\n\n\nBy executing the *glimpse()* function again, I was able to check that `FMEL_UPD_D` has indeed been converted to a date type.\n\n### 3.3 Working with head()\n\nTo reveal complete information of a feature object, I will be using *head()*. I have indicated *n=5* to display only the first five rows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(mpsz, n=5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 5 features and 13 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 103.8131 ymin: 1.274155 xmax: 103.8532 ymax: 1.286506\nGeodetic CRS:  WGS 84\n  OBJECTID_1 SUBZONE_NO     SUBZONE_N SUBZONE_C CA_IND    PLN_AREA_N PLN_AREA_C\n1         21          2 PEOPLE'S PARK    OTSZ02      Y        OUTRAM         OT\n2         22          2   BUKIT MERAH    BMSZ02      N   BUKIT MERAH         BM\n3         23          3     CHINATOWN    OTSZ03      Y        OUTRAM         OT\n4         24          4       PHILLIP    DTSZ04      Y DOWNTOWN CORE         DT\n5         25          5 RAFFLES PLACE    DTSZ05      Y DOWNTOWN CORE         DT\n        REGION_N REGION_C          INC_CRC FMEL_UPD_D SHAPE_1.AREA SHAPE_1.LEN\n1 CENTRAL REGION       CR B4120D23006C932A 2016-05-11     93140.44   1822.1927\n2 CENTRAL REGION       CR 1C51019439A68700 2016-05-11    411722.82   3074.9632\n3 CENTRAL REGION       CR 0FF1661344C84AED 2016-05-11    587222.68   4297.5999\n4 CENTRAL REGION       CR 615D4EDDEF809F8E 2016-05-11     39437.94    871.5549\n5 CENTRAL REGION       CR 72107B11807074F4 2016-05-11    188767.49   1872.7522\n                        geometry\n1 MULTIPOLYGON (((103.8432 1....\n2 MULTIPOLYGON (((103.8221 1....\n3 MULTIPOLYGON (((103.8438 1....\n4 MULTIPOLYGON (((103.8496 1....\n5 MULTIPOLYGON (((103.8525 1....\n```\n\n\n:::\n:::\n\n\n## 4. Plotting the Geospatial Data\n\nUsing *plot()*, you can visualise a data frame by generating coloured maps based on different attributes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(mpsz)\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex01a_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nThe default plot of an sf object is a multi-plot of all attributes, up to a reasonable maximum as shown above. This includes visualisation of non-informative features, such as `OBJECTID_1`.\n\nInstead, you can plot only the geometry by using *st_geometry()* where only the shape and not the attributes are mapped out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(st_geometry(mpsz))\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex01a_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nWe can also plot using a specific attribute, such as `PLN_AREA_N`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(mpsz[\"PLN_AREA_N\"])\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex01a_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nWhen you have more than one layer, you can plot them ontop of each other to visualise more information. I will now plot `preschool` layer ontop of the `mpsz` layer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(st_geometry(mpsz))\nplot(st_geometry(preschool), \n     add = TRUE)\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex01a_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nAs both `preschool` and `mpsz` are in **WGS84**, the preschool points appear on the subzone map. However, the points are too dense and it is difficult to have a detailed interpretation of the exact locations within each subzone. Regardless, it provides a good overview of where preschools are generally not located, namely the industrial areas, nature reserves and offshore islands.\n\nLet's now try plotting the `cyclingpath` layer ontop of the `mpsz` layer, where the former is in **SVY21** while the latter is in **WGS84**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(st_geometry(mpsz))\nplot(st_geometry(cyclingpath),\n     add = TRUE, col = \"Blue\")\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex01a_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nCycling path lines do not appear on the subzone layer due to the different coordinate system used. Hence, projection transformation will need to be performed in order to geoprocess these two sets of data.\n\n## 5. Working with Projection\n\n### 5.1 Transforming projection of mpsz and preschool from WGS84 to SVY21\n\nWhen analysis of geospatial data involves the use of distance and/or area measurement, we will need to transform data from geographic coordinate system to projected coordinate system. The transformation uses the *st_transform()* package, where the reprojection to another coordinate system is done mathematically.\n\nSVY21 is Singapore's official national horizontal geodetic datum and plane coordinate system, and is based on the WGS84 (World Geodetic System 1984) to flatten the curved surface of Earth into metric measurements. We will be referencing an EPSG code to identify specific coordinate reference system (CRS), which in the case of SVY21 is 3414.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz <- st_transform(mpsz, \n                              crs = 3414)\n\nst_geometry(mpsz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeometry set for 323 features \nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21 / Singapore TM\nFirst 5 geometries:\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreschool <- st_transform(preschool, \n                              crs = 3414)\n\nst_geometry(preschool)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeometry set for 2290 features \nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 11810.03 ymin: 25596.33 xmax: 45404.24 ymax: 49300.88\nz_range:       zmin: 0 zmax: 0\nProjected CRS: SVY21 / Singapore TM\nFirst 5 geometries:\n```\n\n\n:::\n:::\n\n\nI will also transform `cyclingpath` to the same EPSG: 3414.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncyclingpath <- st_transform(cyclingpath, crs = 3414)\n```\n:::\n\n\nProjection transformation to SVY21 have been completed for `mpsz` and `preschool`, and they are now ready to be geoprocessed with `cyclingpath` and included for analysis involving distance and area measurements.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(st_geometry(mpsz))\nplot(st_geometry(cyclingpath),\n     add = TRUE, col = \"Blue\")\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex01a_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n`cyclingpath` has now successfully been layered ontop of `mpsz`, where cycling paths are shown in blue on the subzone map.\n\n## 6. Working with Aspatial Data\n\n### 6.1 Importing aspatial data\n\nWhen working with geospatial analysis, we may also process them with aspatial data, where it is not a geospatial data but contains x- and y- coordinates in its data field. I will be using `listings` obtained from Inside Airbnb, which contains listings of Airbnb in Singapore.\n\nSince `listings` is in a csv file format, I will use *read_csv()* from the readr package to import the data set as a tibble data frame called `airbnblistings`. I will also use Base R *list()* to preview the first 10 rows, which is similar to the use of *glimpse()*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nairbnblistings <- read_csv(\"data/aspatial/listings.csv\")\n\nlist(airbnblistings)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n# A tibble: 3,247 × 19\n        id name            host_id host_profile_id host_name neighbourhood_group\n     <dbl> <chr>             <dbl>           <dbl> <chr>     <chr>              \n 1   71609 Ensuite Room (…  3.67e5         1.46e18 Belinda   East Region        \n 2   71896 B&B  Room 1 ne…  3.67e5         1.46e18 Belinda   East Region        \n 3   71903 Room 2-near Ai…  3.67e5         1.46e18 Belinda   East Region        \n 4  294281 5 mins walk fr…  1.52e6         1.46e18 Elizbeth  Central Region     \n 5  344803 Budget short s…  3.67e5         1.46e18 Belinda   East Region        \n 6  369141 5mins from New…  1.52e6         1.46e18 Elizbeth  Central Region     \n 7  369145 5 mins walk fr…  1.52e6         1.46e18 Elizbeth  Central Region     \n 8 4069756 DORMS - In the…  1.75e7         1.46e18 Royal     Central Region     \n 9 4211375 Near NTU Amazi…  1.23e7         1.46e18 Mia       West Region        \n10 4271250 City Ctr_River…  2.22e7         1.46e18 Yong Xing Central Region     \n# ℹ 3,237 more rows\n# ℹ 13 more variables: neighbourhood <chr>, latitude <dbl>, longitude <dbl>,\n#   room_type <chr>, price <dbl>, minimum_nights <dbl>,\n#   number_of_reviews <dbl>, last_review <date>, reviews_per_month <dbl>,\n#   calculated_host_listings_count <dbl>, availability_365 <dbl>,\n#   number_of_reviews_ltm <dbl>, license <chr>\n```\n\n\n:::\n:::\n\n\nFrom the output, `airbnblistings`contains 3247 rows and 19 columns. We will be focusing on the fields `latitude` and `longtitude`, which are in decimal degree format. Based on a quick Google search of the numbers, they fall within the range of WGS 84 coordinate system for Singapore, which uses a latitude range from -90° to +90° and a longitude range from -180° to +180°.\n\n### 6.2 Creating a simple data frame from an aspatial data frame\n\nI will now convert `airbnblistings` into a simple data frame using *st_as_sf()* of sf package. The argument is detailed as follows:\n\n- coords argument requires the column name of the x-coordinates (longitude) first, followed by the y-coordinates (latitude).\n- crs argument requires the coordinates system in EPSG format. EPSG: 4326 is WGS84 Geographic Coordinate System and EPSG: 3414 is Singapore's SVY21 Projected Coordinate System. Other countries' EPSG code by found on epsg.io.\n- %\\>% is used to nest *st_transform()* to transform the newly created simple feature data frame into the SVY21 Projected Coordinate System.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nairbnblistings_sf <- st_as_sf(airbnblistings, \n                       coords = c(\"longitude\", \"latitude\"),\n                       crs=4326) %>%\n  st_transform(crs = 3414)\n```\n:::\n\n\nI will now examine the content of the newly created simple feature data frame `airbnblistings_sf` using *glimpse()*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(airbnblistings_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,247\nColumns: 18\n$ id                             <dbl> 71609, 71896, 71903, 294281, 344803, 36…\n$ name                           <chr> \"Ensuite Room (Room 1 & 2) near EXPO\", …\n$ host_id                        <dbl> 367042, 367042, 367042, 1521514, 367042…\n$ host_profile_id                <dbl> 1.462517e+18, 1.462517e+18, 1.462517e+1…\n$ host_name                      <chr> \"Belinda\", \"Belinda\", \"Belinda\", \"Elizb…\n$ neighbourhood_group            <chr> \"East Region\", \"East Region\", \"East Reg…\n$ neighbourhood                  <chr> \"Tampines\", \"Tampines\", \"Tampines\", \"Ne…\n$ room_type                      <chr> \"Private room\", \"Private room\", \"Privat…\n$ price                          <dbl> NA, NA, NA, 32, 15, NA, 26, 11, 28, 48,…\n$ minimum_nights                 <dbl> 92, 92, 92, 92, 92, 92, 92, 92, 92, 92,…\n$ number_of_reviews              <dbl> 19, 24, 46, 131, 60, 81, 163, 20, 0, 17…\n$ last_review                    <date> 2020-01-17, 2019-10-13, 2020-01-09, 20…\n$ reviews_per_month              <dbl> 0.11, 0.13, 0.25, 0.75, 0.34, 0.52, 0.9…\n$ calculated_host_listings_count <dbl> 5, 5, 5, 7, 5, 7, 7, 4, 2, 1, 8, 1, 73,…\n$ availability_365               <dbl> 90, 90, 90, 364, 364, 364, 364, 364, 36…\n$ number_of_reviews_ltm          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ license                        <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ geometry                       <POINT [m]> POINT (41972.5 36390.05), POINT (…\n```\n\n\n:::\n:::\n\n\nWith the transformation, notice that a new column `geometry` using projected coordinate reference system is created. You will also notice that the fields `latitude` and `longtitude` have been dropped.\n\nI will now plot `airbnblistings_sf` ontop of `mpsz` to visualise Airbnb listings in Singapore subzones.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(st_geometry(mpsz))\nplot(st_geometry(airbnblistings_sf), add = TRUE)\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex01a_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n## 7. Geoprocessing with sf package\n\nBesides functions to handle geospatial data, such as importing, assigning projections and transformations which were shown earlier, sf package offers a wide range of geoprocessing functions. This is also known as Geographic Information System (GIS) analysis.\n\n### 7.1 Use Case 1: land acquisition analysis\n\n**Scenario** The authority is planning to upgrade the exiting cycling path. To do so, they need to acquire 5 meters of reserved land on both sides of the existing cycling path. You are tasked to determine the extend of the land that needs to be acquired and the total area.\n\n**Solution** First, I will use *st_buffer* to compute the 5-meter buffer around the cycling paths. The function is used to expand or shrink vector geometries outward by a specified distance, where the width is defined by the *dist=* referencing the metrics of SVY21. *nQuadSegs* controls the smoothness of and must be an integer more than or equals to 1. Although there is no upper limit, high values may produce negligible visual improvement.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbuffer_cycling <- st_buffer(\n  cyclingpath, dist=5, nQuadSegs = 30)\n```\n:::\n\n\nI will now calculate the area of the buffer using tidyverse.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbuffer_cycling <- buffer_cycling %>%\n  mutate(AREA = st_area(geometry))\n```\n:::\n\n\nLastly, I will use *sum()* to derive the total land needed\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(buffer_cycling$AREA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3687875 [m^2]\n```\n\n\n:::\n:::\n\n\nThe buffer can also be plotted based on a selected planning subzone for the purpose of land acqusition planning, such as Tampines West .\n\nFirst, I will use *filter()* to extract the polygon feature of Tampines West.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_selected <- mpsz %>%\n  filter(SUBZONE_N == \"TAMPINES WEST\")\n```\n:::\n\n\nNext, I will use *st_intersection()* to clip the cycling buffers within Tampines West planning subzone.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbuffer_cycling_selected <- st_intersection(\n  buffer_cycling, mpsz_selected)\n```\n:::\n\n\nLastly, I will use *plot()* to create the plot as shown below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(st_geometry(buffer_cycling_selected))\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex01a_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n### 7.2 Use case 2: To determine the number of pre-schools by planning subzone\n\n**Scenario** The authority requires a count of pre-schools for each planning subzone to support forward planning. Using R and the sf package, perform the necessary geoprocessing to compute these counts and present the results clearly.\n\n**Solution** First, to identify pre-schools located inside each Planning Subzone by using *st_intersects()*. Next, *length()* is used to calculate numbers of pre-schools that fall inside each planning subzone.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz$`PreSch Count`<- lengths(st_intersects(mpsz, preschool))\n```\n:::\n\n\nI will now check the summary statistics of the newly derived `PreSch Count` field by using *summary()*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mpsz$`PreSch Count`)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    0.00    4.00    7.09   10.00   72.00 \n```\n\n\n:::\n:::\n\n\nTo list the planning subzone with the most number of pre-school, the *top_n()* of dplyr package is used.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_n(mpsz, 1, `PreSch Count`)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 14 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 39655.33 ymin: 35966 xmax: 42940.57 ymax: 38622.37\nProjected CRS: SVY21 / Singapore TM\n  OBJECTID_1 SUBZONE_NO     SUBZONE_N SUBZONE_C CA_IND PLN_AREA_N PLN_AREA_C\n1        204          2 TAMPINES EAST    TMSZ02      N   TAMPINES         TM\n     REGION_N REGION_C          INC_CRC FMEL_UPD_D SHAPE_1.AREA SHAPE_1.LEN\n1 EAST REGION       ER 21658EAAF84F4D8D 2016-05-11      4339824    10180.62\n                        geometry PreSch Count\n1 MULTIPOLYGON (((42196.76 38...           72\n```\n\n\n:::\n:::\n\n\nAnother geoprocessing function of sf package called *st_area()* is used to derive the area of each planning subzone.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz$Area <- mpsz %>%\n  st_area()\n```\n:::\n\n\nNext, I will use *mutate()* to compute the density.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz <- mpsz %>%\n  mutate(`PreSch Density` = `PreSch Count`/Area * 1000000)\n```\n:::\n\n\nI will now visualise the derived variables by using exploratory data analysis methods from ggplot2.\n\nFirst, I will plot a histogram to reveal the distribution of `PreSch Density` using *hist()* of R Graphics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(mpsz$`PreSch Density`)\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex01a_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\nAlthough the code chunk is easy to use, the resulting visualisation is not of publication quality. Improvements could be made by including a title and subtitle, having proper x and y labels, defining the bins for better division of data and including colour.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=mpsz, \n       aes(x= as.numeric(`PreSch Density`)))+\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"yellow\") +\n  labs(title = \"Are pre-school evenly distributed in Singapore?\",\n       subtitle= \"There are many planning subzones with a single pre-school. On the other hand, \\nthere are seven planning subzones with at least 30 or more pre-schools.\",\n      x = \"Pre-school density (per km sq)\",\n      y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex01a_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\nI will now use ggplot2 functions to plot a scatterplot showing the relationship between `Pre-school Density` and `Pre-school Count`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=mpsz, \n       aes(y = `PreSch Count`, \n           x= as.numeric(`PreSch Density`)))+\n  geom_point(color=\"black\", \n             fill=\"black\") +\n  xlim(0, 40) +\n  ylim(0, 40) +\n  labs(title = \"\",\n      x = \"Pre-school density (per km sq)\",\n      y = \"Pre-school count\")\n```\n\n::: {.cell-output-display}\n![](Hands-On_Ex01a_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n## 8. Reference\n\nKam, T. S. Geospatial Data Science with R. R for Geospatial Data Science and Analytics. https://r4gdsa.netlify.app/chap01.html\n",
    "supporting": [
      "Hands-On_Ex01a_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}